import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.112.4/+esm';

const URL='https://dmdgkjksouhhsuojthav.supabase.co';
const KEY='sb_publishable_-bZLK1vmL0eUMz65A6EUsw_I20LBq2B';
const sb=createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dt=v=>v?new Date(v).toLocaleString():'—';
const date=v=>v?new Date(v).toLocaleDateString():'—';
const pct=(n,d)=>d?Math.round(n/d*100):0;
const badge=v=>`<span class="ops-badge ${esc(String(v||'').toLowerCase())}">${esc(String(v||'—').replaceAll('_',' '))}</span>`;
const empty=t=>`<div class="ops-empty">${esc(t)}</div>`;
const priorityWeight={critical:4,high:3,normal:2,low:1,urgent:4};
const phaseOrder=['foundation','piloting','operational','gated'];
const permissionOrder=['draft_only','recommend','controlled_internal_write','approved_external_action'];

const state={user:null,errors:[],layers:[],actions:[],canon:[],decisions:[],templates:[],systems:[],connectorHealth:[],workflows:[],runs:[],exceptions:[],agents:[],agentEvals:[],memory:[],evidence:[],experiments:[],improvements:[],incidents:[],tools:[],queue:[],reviews:[],kpis:[],approvals:[],requests:[],projects:[],tasks:[],metrics:[],leads:[]};

function toast(message,bad=false){const el=$('toast');el.textContent=message;el.style.borderColor=bad?'rgba(255,159,159,.4)':'#325978';el.classList.add('show');clearTimeout(window.__opsToast);window.__opsToast=setTimeout(()=>el.classList.remove('show'),3600)}
function showAccess(title,copy,actions=true){$('accessTitle').textContent=title;$('accessCopy').textContent=copy;$('accessActions').style.display=actions?'flex':'none';$('accessView').style.display='grid';$('consoleApp').hidden=true}
function showConsole(){$('accessView').style.display='none';$('consoleApp').hidden=false}
function openModal(eyebrow,title,html){$('modalEyebrow').textContent=eyebrow;$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').classList.add('show');$('modal').setAttribute('aria-hidden','false')}
function closeModal(){$('modal').classList.remove('show');$('modal').setAttribute('aria-hidden','true');$('modalBody').innerHTML=''}
$('modalClose').onclick=closeModal;$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal()});

async function safe(name,promise){try{const {data,error}=await promise;if(error){state.errors.push({name,message:error.message});return []}return data??[]}catch(err){state.errors.push({name,message:err.message||String(err)});return []}}

async function loadData(){
  state.errors=[];
  const [layers,actions,canon,decisions,templates,systems,connectorHealth,workflows,runs,exceptions,agents,agentEvals,memory,evidence,experiments,improvements,incidents,tools,queue,reviews,kpis,approvals,requests,projects,tasks,metrics,leads]=await Promise.all([
    safe('layers',sb.from('nexus_blueprint_layers').select('*').order('layer_no')),
    safe('actions',sb.from('nexus_blueprint_actions').select('*').order('action_no')),
    safe('canon',sb.from('nexus_canon_records').select('*').order('domain').order('title')),
    safe('decisions',sb.from('nexus_decision_register').select('*').order('created_at',{ascending:false}).limit(100)),
    safe('templates',sb.from('nexus_artifact_templates').select('*').order('category').order('title')),
    safe('systems',sb.from('nexus_system_registry').select('*').order('updated_at',{ascending:false}).limit(200)),
    safe('connectorHealth',sb.from('nexus_connector_health').select('*').order('checked_at',{ascending:false}).limit(200)),
    safe('workflows',sb.from('nexus_workflow_definitions').select('*').order('updated_at',{ascending:false}).limit(200)),
    safe('runs',sb.from('nexus_workflow_runs').select('*').order('started_at',{ascending:false}).limit(300)),
    safe('exceptions',sb.from('nexus_workflow_exceptions').select('*').order('detected_at',{ascending:false}).limit(200)),
    safe('agents',sb.from('nexus_agent_registry').select('*').order('title')),
    safe('agentEvals',sb.from('nexus_agent_evaluations').select('*').order('evaluated_at',{ascending:false}).limit(400)),
    safe('memory',sb.from('nexus_memory_records').select('*').order('updated_at',{ascending:false}).limit(200)),
    safe('evidence',sb.from('nexus_evidence_registry').select('*').order('created_at',{ascending:false}).limit(200)),
    safe('experiments',sb.from('nexus_experiments').select('*').order('created_at',{ascending:false}).limit(100)),
    safe('improvements',sb.from('nexus_improvement_ledger').select('*').order('created_at',{ascending:false}).limit(200)),
    safe('incidents',sb.from('nexus_incidents').select('*').order('detected_at',{ascending:false}).limit(200)),
    safe('tools',sb.from('nexus_tool_registry').select('*').order('classification').order('name')),
    safe('queue',sb.from('nexus_founder_decision_queue').select('*').order('created_at',{ascending:false}).limit(200)),
    safe('reviews',sb.from('nexus_operating_reviews').select('*').order('created_at',{ascending:false}).limit(100)),
    safe('kpis',sb.from('nexus_kpi_definitions').select('*').order('domain').order('title')),
    safe('approvals',sb.from('nexus_approvals').select('*').order('created_at',{ascending:false}).limit(200)),
    safe('requests',sb.from('nexus_client_requests').select('*').order('created_at',{ascending:false}).limit(200)),
    safe('projects',sb.from('nexus_projects').select('*').order('updated_at',{ascending:false}).limit(100)),
    safe('tasks',sb.from('nexus_tasks').select('*').order('created_at',{ascending:false}).limit(200)),
    safe('metrics',sb.from('nexus_metrics').select('*').order('created_at',{ascending:false}).limit(200)),
    safe('leads',sb.from('nexus_opportunity_snapshot_leads').select('id,created_at,status,opportunity_score,primary_opportunity,company_name').order('created_at',{ascending:false}).limit(200))
  ]);
  Object.assign(state,{layers,actions,canon,decisions,templates,systems,connectorHealth,workflows,runs,exceptions,agents,agentEvals,memory,evidence,experiments,improvements,incidents,tools,queue,reviews,kpis,approvals,requests,projects,tasks,metrics,leads});
  const chip=$('sourceHealth');if(state.errors.length){chip.textContent=`${state.errors.length} source issue${state.errors.length===1?'':'s'}`;chip.className='ops-chip warn'}else{chip.textContent='Sources current';chip.className='ops-chip good'}
  renderAll();
}

function openFounderQueue(){return state.queue.filter(x=>['open','waiting'].includes(x.status))}
function activeIncidents(){return state.incidents.filter(x=>!['resolved','closed'].includes(x.status))}
function activeExceptions(){return state.exceptions.filter(x=>!['resolved','accepted','closed'].includes(x.status))}
function pendingApprovals(){return state.approvals.filter(x=>x.status==='pending')}
function openRequests(){return state.requests.filter(x=>!['complete','declined'].includes(x.status))}
function openTasks(){return state.tasks.filter(x=>!['done','complete','completed'].includes(x.status))}
function activeProjects(){return state.projects.filter(x=>['planning','active'].includes(x.status))}
function evalStats(code){const rows=state.agentEvals.filter(x=>x.agent_code===code&&x.passed!==null);const passed=rows.filter(x=>x.passed===true).length;return {rows,passed,total:rows.length,passRate:pct(passed,rows.length),adversarialFailed:rows.some(x=>x.case_type==='adversarial'&&x.passed===false)}}
function workflowStats(id){const rows=state.runs.filter(x=>x.workflow_id===id);const complete=rows.filter(x=>x.status==='completed').length,business=rows.filter(x=>x.business_completed===true).length,issues=state.exceptions.filter(x=>x.workflow_id===id&&!['resolved','accepted','closed'].includes(x.status)).length;return {rows,total:rows.length,complete,business,businessRate:pct(business,rows.length),issues}}
function priorityItems(){
  const items=[];
  openFounderQueue().forEach(x=>items.push({kind:'Founder decision',title:x.title,sub:x.context||x.recommended_action||'',priority:x.priority||'normal',when:x.next_review_at||x.due_at,section:'decisions'}));
  activeIncidents().forEach(x=>items.push({kind:'Incident',title:x.title,sub:x.summary||'',priority:x.severity==='critical'?'critical':x.severity==='high'?'high':'normal',when:x.detected_at,section:'improvement'}));
  activeExceptions().forEach(x=>items.push({kind:'Workflow exception',title:x.summary,sub:x.exception_class,priority:x.severity==='critical'?'critical':x.severity==='high'?'high':'normal',when:x.detected_at,section:'workflows'}));
  pendingApprovals().forEach(x=>items.push({kind:'Client approval',title:x.title,sub:x.description||'',priority:'high',when:x.due_date,section:'command'}));
  openRequests().filter(x=>['urgent','high'].includes(x.priority)).forEach(x=>items.push({kind:'Client request',title:x.title,sub:x.description||'',priority:x.priority==='urgent'?'critical':'high',when:x.created_at,section:'command'}));
  return items.sort((a,b)=>(priorityWeight[b.priority]||0)-(priorityWeight[a.priority]||0)||(new Date(a.when||0)-new Date(b.when||0))).slice(0,8);
}
function evidenceSignals(){
  const out=[];
  if(!state.runs.length)out.push({level:'warn',title:'No workflow run evidence yet',copy:'Workflow automation and Managed Operations remain unproven. Keep workflows manual/AI-assisted until run data and exceptions exist.'});
  if(!state.agentEvals.length)out.push({level:'warn',title:'No recorded agent evaluations yet',copy:'The four first agents are correctly still in shadow/draft mode. Permission promotion is blocked until representative tests are recorded.'});
  if(!state.metrics.length)out.push({level:'warn',title:'No client baseline/current metrics yet',copy:'Do not make savings, revenue, or ROI claims. The first commercial pilot still needs a measurable baseline and KPI.'});
  if(!state.improvements.some(x=>x.status==='validated'))out.push({level:'warn',title:'No validated Improvement Ledger result yet',copy:'Relystra has architecture but not yet a defensible before/after case. This is the primary proof gap.'});
  if(!state.evidence.length)out.push({level:'warn',title:'Evidence registry is empty',copy:'Future material claims should be linked to source evidence, measurement windows, confidence, and permission status.'});
  if(!out.length)out.push({level:'good',title:'Core evidence channels populated',copy:'Continue checking attribution, permission, and measurement quality before productizing results.'});
  return out;
}
function domainStats(){return [
  ['Pipeline',state.leads.length+state.requests.filter(x=>x.category==='sales').length,`${state.leads.filter(x=>x.status==='new').length} new Snapshot leads`],
  ['Delivery',activeProjects().length,`${openTasks().length} open actions`],
  ['Managed Ops',state.workflows.filter(x=>x.status==='active').length,`${activeExceptions().length} open exceptions`],
  ['Product / IP',state.templates.length,`${state.actions.filter(x=>x.status==='completed').length} blueprint actions complete`],
  ['Knowledge',state.canon.filter(x=>x.status==='approved').length,`${state.memory.filter(x=>x.status==='latest').length} memory records`],
  ['Proof',state.evidence.length,`${state.improvements.filter(x=>x.status==='validated').length} validated improvements`],
  ['Finance / Capacity',state.kpis.filter(x=>x.domain==='finance_capacity').length,'Baseline founder hours still required'],
  ['Growth',state.leads.length,`${state.leads.length} captured Snapshot leads`]
]}

function renderCommand(){
  const priorities=priorityItems(),signals=evidenceSignals(),passed=state.layers.filter(x=>x.gate_passed).length,foundation=state.actions.filter(x=>['foundation_complete','ready_for_test','completed'].includes(x.status)).length;
  $('commandRoot').innerHTML=`<div class="ops-page-head"><div><div class="eyebrow">Daily Command Brief</div><h1>What requires judgment now?</h1><p>Deterministic synthesis of Relystra operating records. This view surfaces exceptions, approvals, evidence gaps, and founder decisions instead of re-summarizing everything.</p></div><div class="ops-head-actions"><button class="btn primary" id="saveDailyReview" type="button">Save Daily Review</button></div></div>
  <div class="ops-stat-grid"><div class="ops-stat"><strong>${openFounderQueue().length}</strong><span>Founder decisions</span></div><div class="ops-stat"><strong>${pendingApprovals().length}</strong><span>Pending approvals</span></div><div class="ops-stat"><strong>${activeIncidents().length}</strong><span>Open incidents</span></div><div class="ops-stat"><strong>${activeExceptions().length}</strong><span>Workflow exceptions</span></div><div class="ops-stat"><strong>${passed}/10</strong><span>Layer gates passed</span></div><div class="ops-stat"><strong>${foundation}/15</strong><span>Action foundations ready</span></div></div>
  <div class="ops-command"><div class="eyebrow">Top founder priorities</div><h2>${priorities.length?'Resolve the highest-consequence items first.':'No material decision or exception is currently queued.'}</h2><p>Priority is based on explicit founder decisions, critical/high incidents, workflow exceptions, client approvals, and urgent requests.</p><div class="ops-priority-list">${priorities.length?priorities.slice(0,5).map((x,i)=>`<button type="button" class="ops-priority" data-jump="${x.section}"><span class="ops-priority-num">0${i+1}</span><span><b>${esc(x.title)}</b><small>${esc(x.kind)}${x.sub?' · '+esc(x.sub.slice(0,180)):''}</small></span>${badge(x.priority)}</button>`).join(''):empty('No current priority item.')}</div></div>
  <div class="ops-grid"><div class="ops-panel"><div class="ops-panel-head"><div><h2>Evidence & proof gates</h2><p class="ops-section-copy">What Relystra can and cannot responsibly claim today.</p></div></div><div class="ops-list">${signals.map(x=>`<div class="${x.level==='good'?'ops-good':'ops-warning'}"><b>${esc(x.title)}</b><br>${esc(x.copy)}</div>`).join('')}</div></div><div class="ops-panel"><h2>Client operating pressure</h2><div class="ops-risk-list"><div class="ops-risk"><b>Open client requests</b><span>${openRequests().length}</span></div><div class="ops-risk"><b>Pending approvals</b><span>${pendingApprovals().length}</span></div><div class="ops-risk"><b>Open client/project actions</b><span>${openTasks().length}</span></div><div class="ops-risk"><b>Active/planning projects</b><span>${activeProjects().length}</span></div><div class="ops-risk"><b>Captured Snapshot leads</b><span>${state.leads.length}</span></div></div></div></div>
  <div class="ops-grid"><div class="ops-panel" style="grid-column:1/-1"><h2>Eight operating domains</h2><p class="ops-section-copy">The blueprint requires one company OS across pipeline, delivery, managed operations, IP, knowledge, proof, finance/capacity, and growth.</p><div class="ops-grid three">${domainStats().map(([n,v,s])=>`<div class="ops-item"><h3>${esc(n)}</h3><div style="font-size:27px;font-weight:800">${esc(v)}</div><p>${esc(s)}</p></div>`).join('')}</div></div></div>`;
  $('commandRoot').querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>activate(b.dataset.jump));
  $('saveDailyReview').onclick=()=>saveOperatingReview('daily');
}

function renderLayers(){
  $('layersRoot').innerHTML=`<div class="ops-page-head"><div><div class="eyebrow">Blueprint execution</div><h1>Ten layers, one operating stack.</h1><p>A gate is not passed because infrastructure exists. It passes only when the blueprint’s operating evidence standard is demonstrated.</p></div></div><div class="ops-layer-grid">${state.layers.map(l=>`<div class="ops-layer"><div class="ops-layer-top"><span class="ops-layer-no">${String(l.layer_no).padStart(2,'0')}</span><div><div class="ops-meta" style="margin:0 0 7px">${badge(l.phase)}${l.gate_passed?'<span class="ops-badge good">gate passed</span>':'<span class="ops-badge gated">gate open</span>'}</div><h3>${esc(l.title)}</h3><p>${esc(l.target_outcome)}</p></div></div><div class="ops-layer-gate"><b>Execution gate</b><p>${esc(l.gate_standard)}</p>${l.gate_evidence?`<p><strong>Evidence:</strong> ${esc(l.gate_evidence)}</p>`:''}</div><div class="ops-layer-actions"><button class="btn secondary layer-review" data-layer="${l.layer_no}" type="button">Review Gate</button></div></div>`).join('')}</div><div style="height:18px"></div><div class="ops-panel"><div class="ops-panel-head"><div><h2>Immediate Action Register</h2><p class="ops-section-copy">Infrastructure status is separated from evidence completion so “built” is never confused with “proven.”</p></div></div><div class="ops-table-wrap"><table class="ops-table"><thead><tr><th>#</th><th>Action</th><th>Timing</th><th>Status</th><th>Done when</th><th>Next evidence</th><th></th></tr></thead><tbody>${state.actions.map(a=>`<tr><td>${a.action_no}</td><td><b>${esc(a.action)}</b><p>${esc(a.owner_label)}</p></td><td>${esc(a.timing)}</td><td>${badge(a.status)}</td><td>${esc(a.done_when)}</td><td>${esc(a.next_step||a.evidence||'—')}</td><td><button class="btn secondary action-review" data-action="${esc(a.action_code)}" type="button">Review</button></td></tr>`).join('')}</tbody></table></div></div>`;
  document.querySelectorAll('.layer-review').forEach(b=>b.onclick=()=>reviewLayer(Number(b.dataset.layer)));
  document.querySelectorAll('.action-review').forEach(b=>b.onclick=()=>reviewAction(b.dataset.action));
}

function reviewLayer(no){const l=state.layers.find(x=>x.layer_no===no);if(!l)return;openModal(`Layer ${String(no).padStart(2,'0')}`,'Review execution gate',`<div class="ops-warning"><b>Do not mark a gate passed from architecture alone.</b> Record the operating evidence that meets the stated standard.</div><div class="ops-divider"></div><form id="layerForm"><div class="ops-field"><label>Phase</label><select id="layerPhase" class="ops-select">${phaseOrder.map(x=>`<option value="${x}" ${l.phase===x?'selected':''}>${x.replaceAll('_',' ')}</option>`).join('')}</select></div><div class="ops-field" style="margin-top:11px"><label>Gate evidence</label><textarea id="layerEvidence" class="ops-textarea" placeholder="Specific observed evidence, not planned work.">${esc(l.gate_evidence||'')}</textarea></div><label style="display:flex;gap:9px;align-items:center;margin-top:12px;font-size:11px"><input id="layerPassed" type="checkbox" ${l.gate_passed?'checked':''}> Gate standard is demonstrably met</label><div class="ops-form-actions"><button class="btn primary" type="submit">Save gate review</button></div></form>`);$('layerForm').onsubmit=async e=>{e.preventDefault();const passed=$('layerPassed').checked,evidence=$('layerEvidence').value.trim();if(passed&&evidence.length<20)return toast('Gate evidence must be specific before passing a layer.',true);const {error}=await sb.from('nexus_blueprint_layers').update({phase:$('layerPhase').value,gate_passed:passed,gate_evidence:evidence||null,updated_at:new Date().toISOString()}).eq('layer_no',no);if(error)return toast(error.message,true);closeModal();toast('Layer gate reviewed.');await loadData()}}
function reviewAction(code){const a=state.actions.find(x=>x.action_code===code);if(!a)return;const statuses=['not_started','foundation_complete','ready_for_test','in_progress','blocked','completed','gated'];openModal(`Action ${a.action_no}`,'Review blueprint action',`<form id="actionForm"><div class="ops-field"><label>Action</label><div class="ops-good">${esc(a.action)}</div></div><div class="ops-form-grid" style="margin-top:12px"><div class="ops-field"><label>Status</label><select id="actionStatus" class="ops-select">${statuses.map(x=>`<option value="${x}" ${a.status===x?'selected':''}>${x.replaceAll('_',' ')}</option>`).join('')}</select></div><div class="ops-field"><label>Done when</label><div class="ops-small">${esc(a.done_when)}</div></div><div class="ops-field full"><label>Evidence</label><textarea id="actionEvidence" class="ops-textarea">${esc(a.evidence||'')}</textarea></div><div class="ops-field full"><label>Next step</label><textarea id="actionNext" class="ops-textarea">${esc(a.next_step||'')}</textarea></div></div><div class="ops-form-actions"><button class="btn primary" type="submit">Save action review</button></div></form>`);$('actionForm').onsubmit=async e=>{e.preventDefault();const status=$('actionStatus').value,evidence=$('actionEvidence').value.trim();if(status==='completed'&&evidence.length<20)return toast('Completion requires specific evidence.',true);const {error}=await sb.from('nexus_blueprint_actions').update({status,evidence:evidence||null,next_step:$('actionNext').value.trim()||null}).eq('action_code',code);if(error)return toast(error.message,true);closeModal();toast('Action register updated.');await loadData()}}

function renderDecisions(){
  const open=openFounderQueue();
  $('decisionsRoot').innerHTML=`<div class="ops-page-head"><div><div class="eyebrow">Founder Decision Queue</div><h1>Separate judgment from routine work.</h1><p>Only choices with material consequence belong here. Routine tasks stay in project/task systems.</p></div><div class="ops-head-actions"><button id="newDecisionQueue" class="btn primary" type="button">+ Queue Decision</button></div></div><div class="ops-stat-grid"><div class="ops-stat"><strong>${open.length}</strong><span>Open / waiting</span></div><div class="ops-stat"><strong>${open.filter(x=>['critical','high'].includes(x.priority)).length}</strong><span>High consequence</span></div><div class="ops-stat"><strong>${state.decisions.filter(x=>x.status==='active').length}</strong><span>Active recorded decisions</span></div><div class="ops-stat"><strong>${state.decisions.filter(x=>x.status==='pending').length}</strong><span>Pending formal decisions</span></div><div class="ops-stat"><strong>${state.decisions.filter(x=>x.confidence==='low').length}</strong><span>Low-confidence decisions</span></div><div class="ops-stat"><strong>${state.decisions.filter(x=>x.unknowns&&Array.isArray(x.unknowns)&&x.unknowns.length).length}</strong><span>Decisions with unknowns</span></div></div><div class="ops-grid"><div class="ops-panel"><h2>Needs founder judgment</h2><div class="ops-list">${open.length?open.map(q=>`<div class="ops-item"><div class="ops-item-head"><div><h3>${esc(q.title)}</h3><p>${esc(q.context||'')}</p></div>${badge(q.priority)}</div><div class="ops-meta">${badge(q.domain)}${badge(q.status)}<span class="ops-badge">review ${date(q.next_review_at||q.due_at)}</span></div>${q.recommended_action?`<p><b>Recommended:</b> ${esc(q.recommended_action)}</p>`:''}<div class="ops-layer-actions"><button class="btn primary record-decision" data-id="${q.id}" type="button">Record Decision</button><button class="btn secondary defer-decision" data-id="${q.id}" type="button">Defer</button></div></div>`).join(''):empty('No founder decision is currently open.')}</div></div><div class="ops-panel"><h2>Decision Register</h2><div class="ops-list">${state.decisions.length?state.decisions.slice(0,12).map(d=>`<div class="ops-item"><div class="ops-item-head"><h3>${esc(d.title)}</h3>${badge(d.status)}</div><p>${esc(d.decision)}</p><div class="ops-meta">${badge(d.confidence)}${d.company_id?'<span class="ops-badge">client-scoped</span>':'<span class="ops-badge">internal</span>'}<span class="ops-badge">${dt(d.decided_at||d.created_at)}</span></div>${d.next_verification?`<p><b>Next verification:</b> ${esc(d.next_verification)}</p>`:''}</div>`).join(''):empty('No formal decisions recorded yet.')}</div></div></div>`;
  $('newDecisionQueue').onclick=newQueueDecision;document.querySelectorAll('.record-decision').forEach(b=>b.onclick=()=>recordDecision(b.dataset.id));document.querySelectorAll('.defer-decision').forEach(b=>b.onclick=()=>deferDecision(b.dataset.id));
}
function newQueueDecision(){openModal('Founder judgment','Queue a material decision',`<form id="queueForm"><div class="ops-form-grid"><div class="ops-field"><label>Domain</label><select id="qDomain" class="ops-select"><option>pipeline</option><option>delivery</option><option>managed_ops</option><option>product_ip</option><option>knowledge</option><option>proof</option><option>finance_capacity</option><option>growth</option><option>governance</option></select></div><div class="ops-field"><label>Priority</label><select id="qPriority" class="ops-select"><option>normal</option><option>high</option><option>critical</option><option>low</option></select></div><div class="ops-field full"><label>Decision required</label><input id="qTitle" class="ops-input" required></div><div class="ops-field full"><label>Context</label><textarea id="qContext" class="ops-textarea"></textarea></div><div class="ops-field full"><label>Recommended action</label><textarea id="qRec" class="ops-textarea"></textarea></div><div class="ops-field full"><label>Consequence / why founder judgment is required</label><textarea id="qConsequence" class="ops-textarea"></textarea></div><div class="ops-field"><label>Next review</label><input id="qReview" class="ops-input" type="datetime-local"></div><div class="ops-field"><label>Source reference</label><input id="qSource" class="ops-input"></div></div><div class="ops-form-actions"><button class="btn primary" type="submit">Queue decision</button></div></form>`);$('queueForm').onsubmit=async e=>{e.preventDefault();const row={domain:$('qDomain').value,title:$('qTitle').value.trim(),context:$('qContext').value.trim()||null,recommended_action:$('qRec').value.trim()||null,consequence:$('qConsequence').value.trim()||null,source_ref:$('qSource').value.trim()||null,priority:$('qPriority').value,next_review_at:$('qReview').value?new Date($('qReview').value).toISOString():null};const {error}=await sb.from('nexus_founder_decision_queue').insert(row);if(error)return toast(error.message,true);closeModal();toast('Founder decision queued.');await loadData()}}
function recordDecision(id){const q=state.queue.find(x=>x.id===id);if(!q)return;openModal('Decision register','Record the decision and evidence model',`<div class="ops-warning"><b>Facts, assumptions, and unknowns should remain separate.</b> Do not manufacture certainty to close a decision faster.</div><form id="recordDecisionForm" style="margin-top:14px"><div class="ops-form-grid"><div class="ops-field full"><label>Decision title</label><input id="dTitle" class="ops-input" value="${esc(q.title)}" required></div><div class="ops-field full"><label>Decision</label><textarea id="dDecision" class="ops-textarea" required></textarea></div><div class="ops-field"><label>Decision type</label><input id="dType" class="ops-input" value="${esc(q.domain)}"></div><div class="ops-field"><label>Confidence</label><select id="dConfidence" class="ops-select"><option>low</option><option selected>medium</option><option>high</option></select></div><div class="ops-field"><label>Facts — one per line</label><textarea id="dFacts" class="ops-textarea"></textarea></div><div class="ops-field"><label>Assumptions — one per line</label><textarea id="dAssumptions" class="ops-textarea"></textarea></div><div class="ops-field"><label>Unknowns — one per line</label><textarea id="dUnknowns" class="ops-textarea"></textarea></div><div class="ops-field"><label>Evidence refs — one per line</label><textarea id="dEvidence" class="ops-textarea"></textarea></div><div class="ops-field full"><label>What evidence would cause revision?</label><textarea id="dVerify" class="ops-textarea"></textarea></div></div><div class="ops-form-actions"><button class="btn primary" type="submit">Record decision</button></div></form>`);$('recordDecisionForm').onsubmit=async e=>{e.preventDefault();const lines=id=>$(id).value.split('\n').map(x=>x.trim()).filter(Boolean);const row={decision_type:$('dType').value.trim()||q.domain,title:$('dTitle').value.trim(),decision:$('dDecision').value.trim(),facts:lines('dFacts'),assumptions:lines('dAssumptions'),unknowns:lines('dUnknowns'),evidence_refs:lines('dEvidence'),confidence:$('dConfidence').value,status:'active',owner_id:state.user.id,next_verification:$('dVerify').value.trim()||null,decided_at:new Date().toISOString()};const {data,error}=await sb.from('nexus_decision_register').insert(row).select('id').single();if(error)return toast(error.message,true);const qerr=(await sb.from('nexus_founder_decision_queue').update({status:'decided',decision_id:data.id,resolved_at:new Date().toISOString()}).eq('id',id)).error;if(qerr)return toast(qerr.message,true);closeModal();toast('Decision recorded with evidence structure.');await loadData()}}
async function deferDecision(id){const next=new Date(Date.now()+7*86400000).toISOString();const {error}=await sb.from('nexus_founder_decision_queue').update({status:'deferred',next_review_at:next}).eq('id',id);if(error)return toast(error.message,true);toast('Decision deferred for seven days.');await loadData()}

function renderAgents(){
  $('agentsRoot').innerHTML=`<div class="ops-page-head"><div><div class="eyebrow">Bounded digital roles</div><h1>Agents earn permission through evidence.</h1><p>Every agent has a narrow mission, tool boundary, prohibited actions, escalation conditions, and evaluation threshold. The console deliberately blocks broad external autonomy in this foundation release.</p></div></div><div class="ops-grid">${state.agents.map(a=>{const s=evalStats(a.agent_code);return `<div class="ops-panel"><div class="ops-panel-head"><div><div class="ops-meta" style="margin:0 0 7px">${badge(a.operating_mode)}${badge(a.permission_level)}</div><h2>${esc(a.title)}</h2><p class="ops-section-copy">${esc(a.mission)}</p></div><span class="ops-score ${s.total&&s.passRate>=Number(a.evaluation_threshold)?'pass':s.total?'fail':''}">${s.total?s.passRate+'%':'—'}</span></div><div class="ops-permission-ladder">${permissionOrder.map(x=>`<span class="${a.permission_level===x?'current':''}">${x.replaceAll('_',' ')}</span>`).join('')}</div><div class="ops-risk-list"><div class="ops-risk"><b>Evaluations</b><span>${s.passed}/${s.total} passed</span></div><div class="ops-risk"><b>Threshold</b><span>${a.evaluation_threshold}%</span></div><div class="ops-risk"><b>Adversarial failure</b><span>${s.adversarialFailed?'Yes':'No recorded failure'}</span></div></div><div class="ops-layer-actions"><button class="btn primary add-eval" data-agent="${a.agent_code}" type="button">Add Evaluation</button><button class="btn secondary review-agent" data-agent="${a.agent_code}" type="button">Permission Review</button></div></div>`}).join('')}</div>`;
  document.querySelectorAll('.add-eval').forEach(b=>b.onclick=()=>addEvaluation(b.dataset.agent));document.querySelectorAll('.review-agent').forEach(b=>b.onclick=()=>reviewAgent(b.dataset.agent));
}
function addEvaluation(code){const a=state.agents.find(x=>x.agent_code===code);if(!a)return;openModal('Agent evaluation',a.title,`<form id="evalForm"><div class="ops-form-grid"><div class="ops-field"><label>Case type</label><select id="eType" class="ops-select"><option>normal</option><option>edge</option><option>ambiguous</option><option>adversarial</option><option>regression</option></select></div><div class="ops-field"><label>Case reference</label><input id="eRef" class="ops-input" required placeholder="prospect-01 / meeting-03 / seeded-permission-test"></div><div class="ops-field full"><label>Expected behavior</label><textarea id="eExpected" class="ops-textarea"></textarea></div><div class="ops-field"><label>Score 0–100</label><input id="eScore" class="ops-input" type="number" min="0" max="100" step="0.1"></div><div class="ops-field"><label>Passed?</label><select id="ePassed" class="ops-select"><option value="true">Pass</option><option value="false">Fail</option></select></div><div class="ops-field full"><label>Failure class / notes</label><textarea id="eNotes" class="ops-textarea"></textarea></div></div><div class="ops-form-actions"><button class="btn primary" type="submit">Record evaluation</button></div></form>`);$('evalForm').onsubmit=async e=>{e.preventDefault();const score=$('eScore').value===''?null:Number($('eScore').value),passed=$('ePassed').value==='true';const row={agent_code:code,case_type:$('eType').value,case_ref:$('eRef').value.trim(),expected_behavior:$('eExpected').value.trim()||null,score,passed,failure_class:passed?null:($('eNotes').value.trim().slice(0,120)||'evaluation_failure'),notes:$('eNotes').value.trim()||null,intervention_required:!passed,reviewed_by:state.user.id};const {error}=await sb.from('nexus_agent_evaluations').insert(row);if(error)return toast(error.message,true);closeModal();toast('Agent evaluation recorded.');await loadData()}}
function reviewAgent(code){const a=state.agents.find(x=>x.agent_code===code),s=evalStats(code);if(!a)return;const eligibleRecommend=s.total>=3&&s.passRate>=Number(a.evaluation_threshold)&&!s.adversarialFailed,eligibleInternal=s.total>=10&&s.passRate>=Number(a.evaluation_threshold)&&!s.adversarialFailed;openModal('Permission promotion',a.title,`<div class="${eligibleRecommend?'ops-good':'ops-warning'}"><b>Current evidence:</b> ${s.passed}/${s.total} passed (${s.total?s.passRate:0}%). Threshold ${a.evaluation_threshold}%. ${s.adversarialFailed?'An adversarial case has failed.':''}</div><div class="ops-divider"></div><div class="ops-risk-list"><div class="ops-risk"><b>Recommend permission</b><span>${eligibleRecommend?'Eligible':'Requires ≥3 evaluations at threshold with no adversarial failure'}</span></div><div class="ops-risk"><b>Controlled internal write</b><span>${eligibleInternal?'Eligible for human-approved internal pilot':'Requires ≥10 evaluations at threshold with no adversarial failure'}</span></div><div class="ops-risk"><b>Approved external action</b><span>Blocked in foundation release</span></div></div><div class="ops-danger" style="margin-top:14px"><b>External autonomy remains blocked.</b> Legal, financial, access, reputation, client, deployment, deletion, pricing, and scope consequences require an explicitly approved deterministic policy and separate human approval.</div><div class="ops-form-actions"><button id="agentKeepShadow" class="btn secondary" type="button">Keep Draft/Shadow</button>${eligibleRecommend?'<button id="agentRecommend" class="btn primary" type="button">Promote to Recommend</button>':''}${eligibleInternal?'<button id="agentInternal" class="btn secondary" type="button">Allow Controlled Internal Write</button>':''}</div>`);$('agentKeepShadow').onclick=()=>updateAgentPermission(code,'draft_only','shadow');if($('agentRecommend'))$('agentRecommend').onclick=()=>updateAgentPermission(code,'recommend','manual_review');if($('agentInternal'))$('agentInternal').onclick=()=>updateAgentPermission(code,'controlled_internal_write','manual_review')}
async function updateAgentPermission(code,permission,mode){const {error}=await sb.from('nexus_agent_registry').update({permission_level:permission,operating_mode:mode}).eq('agent_code',code);if(error)return toast(error.message,true);closeModal();toast('Agent permission policy updated.');await loadData()}

function renderWorkflows(){
  const totalRuns=state.runs.length,business=state.runs.filter(x=>x.business_completed).length;
  $('workflowsRoot').innerHTML=`<div class="ops-page-head"><div><div class="eyebrow">Workflow engine</div><h1>Business completion, not API success.</h1><p>Every recurring workflow requires an explicit trigger, completion condition, owner, baseline/KPI, validation, exception path, logging, and rollback before automation expands.</p></div><div class="ops-head-actions"><button id="newWorkflow" class="btn primary" type="button">+ Define Workflow</button></div></div><div class="ops-stat-grid"><div class="ops-stat"><strong>${state.workflows.length}</strong><span>Workflow definitions</span></div><div class="ops-stat"><strong>${totalRuns}</strong><span>Recorded runs</span></div><div class="ops-stat"><strong>${pct(business,totalRuns)}%</strong><span>Business completion</span></div><div class="ops-stat"><strong>${activeExceptions().length}</strong><span>Open exceptions</span></div><div class="ops-stat"><strong>${state.workflows.filter(x=>x.mode==='automated').length}</strong><span>Automated workflows</span></div><div class="ops-stat"><strong>${state.workflows.filter(x=>['manual','ai_assisted'].includes(x.mode)).length}</strong><span>Manual / AI-assisted</span></div></div><div class="ops-grid">${state.workflows.length?state.workflows.map(w=>{const s=workflowStats(w.id);return `<div class="ops-panel"><div class="ops-panel-head"><div><div class="ops-meta" style="margin:0 0 7px">${badge(w.mode)}${badge(w.status)}</div><h2>${esc(w.name)}</h2><p class="ops-section-copy">${esc(w.purpose)}</p></div></div><div class="ops-risk-list"><div class="ops-risk"><b>Owner</b><span>${esc(w.owner_label)}</span></div><div class="ops-risk"><b>Runs</b><span>${s.total}</span></div><div class="ops-risk"><b>Business completion</b><span>${s.total?s.businessRate+'%':'No evidence'}</span></div><div class="ops-risk"><b>Open exceptions</b><span>${s.issues}</span></div><div class="ops-risk"><b>KPI</b><span>${esc(w.kpi_definition||'Not defined')}</span></div></div><div class="ops-layer-actions"><button class="btn primary log-run" data-workflow="${w.id}" type="button">Log Manual Run</button><button class="btn secondary workflow-detail" data-workflow="${w.id}" type="button">Review Definition</button></div></div>`}).join(''):empty('No workflow has been defined yet. The blueprint requires manual SOPs before automation.')}</div>${activeExceptions().length?`<div class="ops-panel" style="margin-top:14px"><h2>Open exception queue</h2><div class="ops-list">${activeExceptions().map(x=>`<div class="ops-item"><div class="ops-item-head"><h3>${esc(x.summary)}</h3>${badge(x.severity)}</div><div class="ops-meta">${badge(x.exception_class)}${badge(x.status)}<span class="ops-badge">${dt(x.detected_at)}</span></div></div>`).join('')}</div></div>`:''}`;
  $('newWorkflow').onclick=newWorkflow;document.querySelectorAll('.log-run').forEach(b=>b.onclick=()=>logWorkflowRun(b.dataset.workflow));document.querySelectorAll('.workflow-detail').forEach(b=>b.onclick=()=>workflowDetail(b.dataset.workflow));
}
function newWorkflow(){openModal('Workflow standard','Define a manual-first workflow',`<div class="ops-warning"><b>Automation is not the default.</b> Start manual or AI-assisted until the real exception pattern is known.</div><form id="workflowForm" style="margin-top:14px"><div class="ops-form-grid"><div class="ops-field"><label>Workflow code</label><input id="wCode" class="ops-input" required placeholder="discovery_recap"></div><div class="ops-field"><label>Name</label><input id="wName" class="ops-input" required></div><div class="ops-field full"><label>Purpose / business outcome</label><textarea id="wPurpose" class="ops-textarea" required></textarea></div><div class="ops-field"><label>Owner</label><input id="wOwner" class="ops-input" value="Founder" required></div><div class="ops-field"><label>Mode</label><select id="wMode" class="ops-select"><option>manual</option><option>ai_assisted</option><option>shadow</option></select></div><div class="ops-field"><label>Trigger</label><textarea id="wTrigger" class="ops-textarea" required></textarea></div><div class="ops-field"><label>Business completion condition</label><textarea id="wComplete" class="ops-textarea" required></textarea></div><div class="ops-field"><label>Baseline definition</label><textarea id="wBaseline" class="ops-textarea"></textarea></div><div class="ops-field"><label>KPI definition</label><textarea id="wKpi" class="ops-textarea"></textarea></div><div class="ops-field full"><label>Rollback / manual fallback</label><textarea id="wRollback" class="ops-textarea"></textarea></div></div><div class="ops-form-actions"><button class="btn primary" type="submit">Create manual-first definition</button></div></form>`);$('workflowForm').onsubmit=async e=>{e.preventDefault();const row={workflow_code:$('wCode').value.trim().toLowerCase().replace(/[^a-z0-9_]+/g,'_'),name:$('wName').value.trim(),purpose:$('wPurpose').value.trim(),owner_label:$('wOwner').value.trim(),trigger_definition:$('wTrigger').value.trim(),completion_condition:$('wComplete').value.trim(),baseline_definition:$('wBaseline').value.trim()||null,kpi_definition:$('wKpi').value.trim()||null,rollback_procedure:$('wRollback').value.trim()||null,mode:$('wMode').value,status:'testing',created_by:state.user.id};const {error}=await sb.from('nexus_workflow_definitions').insert(row);if(error)return toast(error.message,true);closeModal();toast('Workflow definition created in testing mode.');await loadData()}}
function logWorkflowRun(id){const w=state.workflows.find(x=>x.id===id);if(!w)return;openModal('Manual run evidence',w.name,`<form id="runForm"><div class="ops-form-grid"><div class="ops-field"><label>Run result</label><select id="rStatus" class="ops-select"><option value="completed">Completed</option><option value="failed">Failed</option><option value="needs_review">Needs review</option><option value="cancelled">Cancelled</option></select></div><div class="ops-field"><label>Business completion achieved?</label><select id="rBusiness" class="ops-select"><option value="true">Yes</option><option value="false">No</option></select></div><div class="ops-field"><label>Manual minutes</label><input id="rMinutes" class="ops-input" type="number" min="0" step="0.1"></div><div class="ops-field"><label>Quality score 0–100</label><input id="rQuality" class="ops-input" type="number" min="0" max="100" step="0.1"></div><div class="ops-field"><label>KPI value</label><input id="rKpi" class="ops-input" type="number" step="any"></div><div class="ops-field"><label>Output/evidence reference</label><input id="rRef" class="ops-input"></div><div class="ops-field full"><label>Error / exception summary</label><textarea id="rError" class="ops-textarea"></textarea></div></div><div class="ops-form-actions"><button class="btn primary" type="submit">Record run</button></div></form>`);$('runForm').onsubmit=async e=>{e.preventDefault();const status=$('rStatus').value,business=$('rBusiness').value==='true',errorSummary=$('rError').value.trim()||null,row={workflow_id:id,company_id:w.company_id||null,project_id:w.project_id||null,status,business_completed:business,started_at:new Date().toISOString(),completed_at:new Date().toISOString(),manual_minutes:$('rMinutes').value===''?null:Number($('rMinutes').value),quality_score:$('rQuality').value===''?null:Number($('rQuality').value),kpi_value:$('rKpi').value===''?null:Number($('rKpi').value),output_ref:$('rRef').value.trim()||null,error_summary:errorSummary,intervention_required:status!=='completed'||!business};const {error}=await sb.from('nexus_workflow_runs').insert(row);if(error)return toast(error.message,true);if(errorSummary||status==='failed'||!business){await sb.from('nexus_workflow_exceptions').insert({workflow_id:id,company_id:w.company_id||null,exception_class:status==='failed'?'execution_failure':'business_completion_gap',severity:status==='failed'?'high':'medium',summary:errorSummary||'Run did not meet the business completion condition.',owner_label:w.owner_label,status:'open'})}closeModal();toast('Workflow run recorded.');await loadData()}}
function workflowDetail(id){const w=state.workflows.find(x=>x.id===id),s=workflowStats(id);if(!w)return;openModal('Workflow definition',w.name,`<div class="ops-risk-list"><div class="ops-risk"><b>Purpose</b><span>${esc(w.purpose)}</span></div><div class="ops-risk"><b>Trigger</b><span>${esc(w.trigger_definition)}</span></div><div class="ops-risk"><b>Business completion</b><span>${esc(w.completion_condition)}</span></div><div class="ops-risk"><b>Baseline</b><span>${esc(w.baseline_definition||'Not defined')}</span></div><div class="ops-risk"><b>KPI</b><span>${esc(w.kpi_definition||'Not defined')}</span></div><div class="ops-risk"><b>Rollback</b><span>${esc(w.rollback_procedure||'Not defined')}</span></div><div class="ops-risk"><b>Recorded runs</b><span>${s.total}</span></div><div class="ops-risk"><b>Business completion rate</b><span>${s.total?s.businessRate+'%':'No evidence'}</span></div></div><div class="ops-warning" style="margin-top:14px">Automated mode should not be selected until repeatable runs, exception classes, failure alerts, and rollback are demonstrated. The console does not auto-promote workflow mode.</div>`)}

function renderMemory(){
  const byClass=cls=>state.memory.filter(x=>x.memory_class===cls&&x.status==='latest').length;
  $('memoryRoot').innerHTML=`<div class="ops-page-head"><div><div class="eyebrow">Institutional memory</div><h1>Latest truth, provenance, approval, supersession.</h1><p>Semantic retrieval can surface candidates; source documents and authoritative records remain the truth. Conflicting sources must be surfaced rather than silently reconciled.</p></div><div class="ops-head-actions"><button id="newEvidence" class="btn primary" type="button">+ Register Evidence</button></div></div><div class="ops-stat-grid"><div class="ops-stat"><strong>${state.canon.filter(x=>x.status==='approved').length}</strong><span>Approved canon records</span></div><div class="ops-stat"><strong>${byClass('client_specific')}</strong><span>Client memory</span></div><div class="ops-stat"><strong>${byClass('reusable_pattern')}</strong><span>Reusable patterns</span></div><div class="ops-stat"><strong>${byClass('operational_event')}</strong><span>Operational events</span></div><div class="ops-stat"><strong>${state.evidence.length}</strong><span>Evidence records</span></div><div class="ops-stat"><strong>${state.decisions.length}</strong><span>Decisions recorded</span></div></div><div class="ops-grid"><div class="ops-panel"><h2>Relystra Company Canon</h2><div class="ops-canon-grid">${state.canon.filter(x=>x.status==='approved').map(c=>`<div class="ops-canon"><div class="ops-meta">${badge(c.domain)}<span class="ops-badge">v${c.version}</span></div><h3>${esc(c.title)}</h3><p>${esc(c.content)}</p><div class="ops-small">Source: ${esc(c.source_ref)}</div></div>`).join('')}</div></div><div class="ops-panel"><h2>Recent evidence</h2><div class="ops-list">${state.evidence.length?state.evidence.slice(0,15).map(e=>`<div class="ops-item"><div class="ops-item-head"><h3>${esc(e.title)}</h3>${badge(e.confidence)}</div><p>${esc(e.supports_claim||'Evidence registered; claim link not yet described.')}</p><div class="ops-meta">${badge(e.evidence_type)}${badge(e.permission_status)}<span class="ops-badge">${esc(e.source_ref)}</span></div>${e.limitations?`<p><b>Limits:</b> ${esc(e.limitations)}</p>`:''}</div>`).join(''):empty('No evidence is registered yet.')}</div></div></div><div class="ops-panel" style="margin-top:14px"><h2>Memory architecture status</h2><div class="ops-risk-list"><div class="ops-risk"><b>Canonical</b><span>${byClass('canonical')}</span></div><div class="ops-risk"><b>Client-specific</b><span>${byClass('client_specific')}</span></div><div class="ops-risk"><b>Reusable pattern</b><span>${byClass('reusable_pattern')}</span></div><div class="ops-risk"><b>Operational event</b><span>${byClass('operational_event')}</span></div><div class="ops-risk"><b>Temporary</b><span>${byClass('temporary')}</span></div></div><p class="ops-small">The separate approved Company Canon above remains the canonical policy/strategy index; memory records are task/context records with provenance and supersession metadata.</p></div>`;
  $('newEvidence').onclick=newEvidence;
}
function newEvidence(){openModal('Evidence registry','Register source-grounded evidence',`<form id="evidenceForm"><div class="ops-form-grid"><div class="ops-field"><label>Evidence type</label><input id="evType" class="ops-input" placeholder="baseline, log, metric, approval, screenshot, testimonial"></div><div class="ops-field"><label>Confidence</label><select id="evConfidence" class="ops-select"><option>unrated</option><option>low</option><option>medium</option><option>high</option></select></div><div class="ops-field full"><label>Title</label><input id="evTitle" class="ops-input" required></div><div class="ops-field full"><label>Source reference</label><input id="evRef" class="ops-input" required placeholder="document URL/id, metric record, log ref, approval id"></div><div class="ops-field full"><label>What claim does this support?</label><textarea id="evClaim" class="ops-textarea"></textarea></div><div class="ops-field full"><label>Limitations / attribution caution</label><textarea id="evLimit" class="ops-textarea"></textarea></div><div class="ops-field"><label>Permission</label><select id="evPermission" class="ops-select"><option>internal_only</option><option>client_approved</option><option>public_approved</option></select></div><div class="ops-field"><label>Client visible?</label><select id="evVisible" class="ops-select"><option value="false">No</option><option value="true">Yes</option></select></div></div><div class="ops-form-actions"><button class="btn primary" type="submit">Register evidence</button></div></form>`);$('evidenceForm').onsubmit=async e=>{e.preventDefault();const row={evidence_type:$('evType').value.trim()||'general',title:$('evTitle').value.trim(),source_ref:$('evRef').value.trim(),supports_claim:$('evClaim').value.trim()||null,confidence:$('evConfidence').value,limitations:$('evLimit').value.trim()||null,permission_status:$('evPermission').value,client_visible:$('evVisible').value==='true',created_by:state.user.id};const {error}=await sb.from('nexus_evidence_registry').insert(row);if(error)return toast(error.message,true);closeModal();toast('Evidence registered.');await loadData()}}

function renderImprovement(){
  $('improvementRoot').innerHTML=`<div class="ops-page-head"><div><div class="eyebrow">Evidence compounding</div><h1>Every result or failure should change the system.</h1><p>The Improvement Engine records baseline, intervention, result, attribution, lesson, incident/CAPA, and the next hypothesis. Negative results remain visible.</p></div><div class="ops-head-actions"><button id="newImprovement" class="btn primary" type="button">+ Improvement Entry</button><button id="newIncident" class="btn secondary" type="button">+ Incident</button></div></div><div class="ops-stat-grid"><div class="ops-stat"><strong>${state.improvements.length}</strong><span>Ledger entries</span></div><div class="ops-stat"><strong>${state.improvements.filter(x=>x.status==='validated').length}</strong><span>Validated changes</span></div><div class="ops-stat"><strong>${state.improvements.filter(x=>x.status==='rejected').length}</strong><span>Rejected hypotheses</span></div><div class="ops-stat"><strong>${state.experiments.filter(x=>x.status==='running').length}</strong><span>Running experiments</span></div><div class="ops-stat"><strong>${activeIncidents().length}</strong><span>Open incidents</span></div><div class="ops-stat"><strong>${state.incidents.filter(x=>['resolved','closed'].includes(x.status)&&x.preventive_action).length}</strong><span>Incidents with prevention</span></div></div><div class="ops-grid"><div class="ops-panel"><h2>Improvement Ledger</h2><div class="ops-list">${state.improvements.length?state.improvements.map(i=>`<div class="ops-item"><div class="ops-item-head"><div><h3>${esc(i.title)}</h3><p>${esc(i.change_summary)}</p></div>${badge(i.status)}</div><div class="ops-meta">${badge(i.attribution_confidence)}${i.kpi_name?`<span class="ops-badge">${esc(i.kpi_name)}</span>`:''}</div>${i.actual_result?`<p><b>Observed:</b> ${esc(i.actual_result)}</p>`:''}${i.attribution_note?`<p><b>Attribution:</b> ${esc(i.attribution_note)}</p>`:''}${i.lesson?`<p><b>Learning:</b> ${esc(i.lesson)}</p>`:''}</div>`).join(''):empty('No improvement result has been recorded yet.')}</div></div><div class="ops-panel"><h2>Incident / CAPA</h2><div class="ops-list">${state.incidents.length?state.incidents.slice(0,20).map(i=>`<div class="ops-item"><div class="ops-item-head"><h3>${esc(i.title)}</h3>${badge(i.severity)}</div><p>${esc(i.summary)}</p><div class="ops-meta">${badge(i.status)}<span class="ops-badge">${dt(i.detected_at)}</span></div>${i.root_cause?`<p><b>Root cause:</b> ${esc(i.root_cause)}</p>`:''}${i.preventive_action?`<p><b>Preventive action:</b> ${esc(i.preventive_action)}</p>`:''}</div>`).join(''):empty('No incidents recorded.')}</div></div></div>`;
  $('newImprovement').onclick=newImprovement;$('newIncident').onclick=newIncident;
}
function newImprovement(){openModal('Improvement Ledger','Record a change hypothesis and result',`<form id="improvementForm"><div class="ops-form-grid"><div class="ops-field full"><label>Title</label><input id="iTitle" class="ops-input" required></div><div class="ops-field full"><label>Change / intervention</label><textarea id="iChange" class="ops-textarea" required></textarea></div><div class="ops-field"><label>Baseline reference</label><input id="iBaseline" class="ops-input"></div><div class="ops-field"><label>KPI</label><input id="iKpi" class="ops-input"></div><div class="ops-field"><label>Hypothesis</label><textarea id="iHypothesis" class="ops-textarea"></textarea></div><div class="ops-field"><label>Expected result</label><textarea id="iExpected" class="ops-textarea"></textarea></div><div class="ops-field"><label>Actual observed result</label><textarea id="iActual" class="ops-textarea"></textarea></div><div class="ops-field"><label>Attribution confidence</label><select id="iConfidence" class="ops-select"><option>unrated</option><option>low</option><option>medium</option><option>high</option></select></div><div class="ops-field full"><label>Attribution note / alternative causes</label><textarea id="iAttribution" class="ops-textarea"></textarea></div><div class="ops-field"><label>Status</label><select id="iStatus" class="ops-select"><option>planned</option><option>running</option><option>reviewed</option><option>validated</option><option>rejected</option></select></div><div class="ops-field"><label>Client visible?</label><select id="iVisible" class="ops-select"><option value="false">No</option><option value="true">Yes</option></select></div><div class="ops-field full"><label>Lesson / next action</label><textarea id="iLesson" class="ops-textarea"></textarea></div></div><div class="ops-form-actions"><button class="btn primary" type="submit">Save Improvement entry</button></div></form>`);$('improvementForm').onsubmit=async e=>{e.preventDefault();const status=$('iStatus').value,actual=$('iActual').value.trim(),attribution=$('iAttribution').value.trim();if(status==='validated'&&(!actual||attribution.length<15))return toast('Validated status requires an observed result and attribution note.',true);const row={title:$('iTitle').value.trim(),baseline_ref:$('iBaseline').value.trim()||null,change_summary:$('iChange').value.trim(),hypothesis:$('iHypothesis').value.trim()||null,expected_result:$('iExpected').value.trim()||null,actual_result:actual||null,kpi_name:$('iKpi').value.trim()||null,attribution_confidence:$('iConfidence').value,attribution_note:attribution||null,lesson:$('iLesson').value.trim()||null,status,client_visible:$('iVisible').value==='true',created_by:state.user.id,reviewed_at:['reviewed','validated','rejected'].includes(status)?new Date().toISOString():null};const {error}=await sb.from('nexus_improvement_ledger').insert(row);if(error)return toast(error.message,true);closeModal();toast('Improvement entry saved.');await loadData()}}
function newIncident(){openModal('Incident / CAPA','Record a failure without hiding it',`<form id="incidentForm"><div class="ops-form-grid"><div class="ops-field"><label>Entity type</label><input id="inEntity" class="ops-input" placeholder="workflow, agent, portal, delivery" required></div><div class="ops-field"><label>Severity</label><select id="inSeverity" class="ops-select"><option>low</option><option selected>medium</option><option>high</option><option>critical</option></select></div><div class="ops-field full"><label>Title</label><input id="inTitle" class="ops-input" required></div><div class="ops-field full"><label>What happened?</label><textarea id="inSummary" class="ops-textarea" required></textarea></div><div class="ops-field full"><label>Business impact</label><textarea id="inImpact" class="ops-textarea"></textarea></div><div class="ops-field full"><label>Immediate corrective action</label><textarea id="inCorrective" class="ops-textarea"></textarea></div></div><div class="ops-form-actions"><button class="btn primary" type="submit">Record incident</button></div></form>`);$('incidentForm').onsubmit=async e=>{e.preventDefault();const row={entity_type:$('inEntity').value.trim(),severity:$('inSeverity').value,title:$('inTitle').value.trim(),summary:$('inSummary').value.trim(),business_impact:$('inImpact').value.trim()||null,corrective_action:$('inCorrective').value.trim()||null,status:'open',created_by:state.user.id};const {error}=await sb.from('nexus_incidents').insert(row);if(error)return toast(error.message,true);closeModal();toast('Incident recorded.');await loadData()}}

function renderTools(){
  $('toolsRoot').innerHTML=`<div class="ops-page-head"><div><div class="eyebrow">Tool governance</div><h1>No tool without a bottleneck and value case.</h1><p>The inventory records purpose, owner, data categories, security review, measurable value, and exit path. Unknown costs stay unknown rather than invented.</p></div></div><div class="ops-stat-grid"><div class="ops-stat"><strong>${state.tools.length}</strong><span>Registered tools</span></div><div class="ops-stat"><strong>${state.tools.filter(x=>x.classification==='core').length}</strong><span>Core</span></div><div class="ops-stat"><strong>${state.tools.filter(x=>x.classification==='client_dependent').length}</strong><span>Client-dependent</span></div><div class="ops-stat"><strong>${state.tools.filter(x=>x.classification==='experimental').length}</strong><span>Experimental</span></div><div class="ops-stat"><strong>${state.tools.filter(x=>x.classification==='retire').length}</strong><span>Retire / rollback only</span></div><div class="ops-stat"><strong>${state.tools.filter(x=>x.security_review_status==='pending').length}</strong><span>Security reviews pending</span></div></div><div class="ops-panel"><div class="ops-table-wrap"><table class="ops-table"><thead><tr><th>Tool</th><th>Class</th><th>Purpose</th><th>Security</th><th>Measured value</th><th>Exit path</th><th>Review</th></tr></thead><tbody>${state.tools.map(t=>`<tr><td><b>${esc(t.name)}</b><p>${esc(t.category)}</p></td><td>${badge(t.classification)}${badge(t.status)}</td><td>${esc(t.purpose)}</td><td>${badge(t.security_review_status)}<p>${esc(t.data_categories||'No data categories documented')}</p></td><td>${esc(t.measurable_value||'Not yet measured')}</td><td>${esc(t.exit_path||'Not documented')}</td><td><button class="btn secondary tool-review" data-tool="${t.tool_code}" type="button">Review</button></td></tr>`).join('')}</tbody></table></div></div><div class="ops-warning" style="margin-top:14px"><b>$0 additional internal software rule remains active.</b> This console does not purchase or recommend new subscriptions merely because a capability exists.</div>`;
  document.querySelectorAll('.tool-review').forEach(b=>b.onclick=()=>reviewTool(b.dataset.tool));
}
function reviewTool(code){const t=state.tools.find(x=>x.tool_code===code);if(!t)return;openModal('Quarterly Tool Decision Card',t.name,`<form id="toolForm"><div class="ops-form-grid"><div class="ops-field"><label>Classification</label><select id="tClass" class="ops-select">${['core','client_dependent','experimental','retire'].map(x=>`<option ${t.classification===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="ops-field"><label>Security review</label><select id="tSecurity" class="ops-select">${['pending','reviewed','restricted','not_applicable'].map(x=>`<option ${t.security_review_status===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="ops-field full"><label>Purpose</label><textarea id="tPurpose" class="ops-textarea">${esc(t.purpose)}</textarea></div><div class="ops-field full"><label>What measurable value does it create?</label><textarea id="tValue" class="ops-textarea">${esc(t.measurable_value||'')}</textarea></div><div class="ops-field full"><label>Export / exit path</label><textarea id="tExit" class="ops-textarea">${esc(t.exit_path||'')}</textarea></div><div class="ops-field"><label>Next review</label><input id="tNext" class="ops-input" type="date" value="${t.next_review_at?String(t.next_review_at).slice(0,10):''}"></div><div class="ops-field"><label>Known monthly cost cents (leave blank if unknown)</label><input id="tCost" class="ops-input" type="number" min="0" value="${t.monthly_cost_cents??''}"></div></div><div class="ops-form-actions"><button class="btn primary" type="submit">Save Tool Decision Card</button></div></form>`);$('toolForm').onsubmit=async e=>{e.preventDefault();const value=$('tValue').value.trim(),exit=$('tExit').value.trim();if($('tClass').value==='core'&&(!value||!exit))return toast('Core tools require a measurable-value statement and exit path.',true);const row={classification:$('tClass').value,security_review_status:$('tSecurity').value,purpose:$('tPurpose').value.trim(),measurable_value:value||null,exit_path:exit||null,next_review_at:$('tNext').value?new Date($('tNext').value+'T12:00:00Z').toISOString():null,monthly_cost_cents:$('tCost').value===''?null:Number($('tCost').value),last_roi_review_at:new Date().toISOString()};const {error}=await sb.from('nexus_tool_registry').update(row).eq('tool_code',code);if(error)return toast(error.message,true);closeModal();toast('Tool Decision Card updated.');await loadData()}}

function reviewSnapshot(type){return {generated_at:new Date().toISOString(),founder_decisions:openFounderQueue().length,pending_approvals:pendingApprovals().length,open_requests:openRequests().length,open_tasks:openTasks().length,active_projects:activeProjects().length,workflow_runs:state.runs.length,workflow_exceptions:activeExceptions().length,open_incidents:activeIncidents().length,agent_evaluations:state.agentEvals.length,validated_improvements:state.improvements.filter(x=>x.status==='validated').length,evidence_records:state.evidence.length,blueprint_gates_passed:state.layers.filter(x=>x.gate_passed).length,source_errors:state.errors,review_type:type}}
async function saveOperatingReview(type){const priorities=priorityItems().slice(0,5).map(x=>({title:x.title,kind:x.kind,priority:x.priority}));const row={review_type:type,period_start:new Date().toISOString().slice(0,10),period_end:new Date().toISOString().slice(0,10),snapshot:reviewSnapshot(type),decisions:openFounderQueue().slice(0,10).map(x=>({id:x.id,title:x.title,priority:x.priority,status:x.status})),followups:priorities,status:'complete',created_by:state.user.id,completed_at:new Date().toISOString()};const {error}=await sb.from('nexus_operating_reviews').insert(row);if(error)return toast(error.message,true);toast(`${type.replace('_',' ')} review snapshot saved.`);await loadData()}
function renderReviews(){
  $('reviewsRoot').innerHTML=`<div class="ops-page-head"><div><div class="eyebrow">Management cadence</div><h1>Daily → Weekly → Monthly → Quarterly.</h1><p>Reviews should close loops and create decisions. They are not decorative reports.</p></div><div class="ops-head-actions"><button class="btn primary review-save" data-type="weekly" type="button">Save Weekly Review</button><button class="btn secondary review-save" data-type="monthly" type="button">Save Monthly Review</button><button class="btn secondary review-save" data-type="quarterly" type="button">Save Quarterly Review</button><button class="btn secondary review-save" data-type="architecture" type="button">Save Architecture Review</button></div></div><div class="ops-grid"><div class="ops-panel"><h2>Review history</h2><div class="ops-list">${state.reviews.length?state.reviews.slice(0,25).map(r=>`<div class="ops-item"><div class="ops-item-head"><h3>${esc(r.review_type.replaceAll('_',' '))} review</h3>${badge(r.status)}</div><p>${r.top_constraint?`Top constraint: ${esc(r.top_constraint)}`:'Snapshot stored for the operating period.'}</p><div class="ops-meta"><span class="ops-badge">${dt(r.completed_at||r.created_at)}</span><span class="ops-badge">${Number(r.snapshot?.founder_decisions||0)} founder decisions</span><span class="ops-badge">${Number(r.snapshot?.open_incidents||0)} incidents</span></div></div>`).join(''):empty('No operating reviews saved yet.')}</div></div><div class="ops-panel"><h2>Actionable KPI definitions</h2><div class="ops-list">${state.kpis.map(k=>`<div class="ops-item"><div class="ops-item-head"><h3>${esc(k.title)}</h3>${badge(k.domain)}</div><p>${esc(k.definition)}</p><p><b>Response:</b> ${esc(k.response_rule)}</p><div class="ops-meta"><span class="ops-badge">${esc(k.unit||'context')}</span><span class="ops-badge">source: ${esc(k.source_system||'not assigned')}</span></div></div>`).join('')}</div></div></div><div class="ops-warning" style="margin-top:14px"><b>Review timing:</b> the database stores the cadence and snapshots. Separate scheduled reminders are used for 30/60/90 architecture gates so the operating review occurs even when the dashboard is not open.</div>`;
  document.querySelectorAll('.review-save').forEach(b=>b.onclick=()=>saveOperatingReview(b.dataset.type));
}

function renderAll(){renderCommand();renderLayers();renderDecisions();renderAgents();renderWorkflows();renderMemory();renderImprovement();renderTools();renderReviews()}
function activate(section){document.querySelectorAll('.ops-native-section').forEach(s=>s.classList.toggle('active',s.id===`section-${section}`));document.querySelectorAll('#opsNav button').forEach(b=>b.classList.toggle('active',b.dataset.section===section));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('#opsNav button').forEach(b=>b.onclick=()=>activate(b.dataset.section));$('refreshBtn').onclick=()=>loadData();$('signOutBtn').onclick=async()=>{await sb.auth.signOut();location.href='/portal'};

async function init(){
  showAccess('Checking authorized access…','The AI-native operations console is restricted to authorized Relystra platform administrators.',false);
  try{
    const {data:{session},error}=await sb.auth.getSession();if(error)throw error;
    if(!session?.user)return showAccess('Sign in through the Relystra Portal.','This founder console uses the same authenticated Relystra session. Sign in first, then return to /operations.',true);
    state.user=session.user;
    const {data:admin,error:adminError}=await sb.rpc('nexus_is_platform_admin');if(adminError)throw adminError;
    if(admin!==true)return showAccess('Access denied.','Your Relystra account is authenticated but is not authorized for the founder control plane.',true);
    showConsole();await loadData();
  }catch(err){console.error(err);showAccess('The operations console could not initialize.',err.message||'Authentication or data access failed.',true)}
}
init();
