import{S,$,bootSession,loadCloud,loadModules,initNav,go}from'https://dmdgkjksouhhsuojthav.supabase.co/functions/v1/hlo-app?asset=core.js';
import{initAuth,openAfterAuth}from'https://dmdgkjksouhhsuojthav.supabase.co/functions/v1/hlo-app?asset=auth.js';
import{renderDashboard}from'https://dmdgkjksouhhsuojthav.supabase.co/functions/v1/hlo-app?asset=dashboard.js';
import{renderAcademy,openModule}from'https://dmdgkjksouhhsuojthav.supabase.co/functions/v1/hlo-app?asset=academy.js';
import{renderPath}from'https://dmdgkjksouhhsuojthav.supabase.co/functions/v1/hlo-app?asset=personalize.js';
import{renderTutor,renderMastery}from'https://dmdgkjksouhhsuojthav.supabase.co/functions/v1/hlo-app?asset=learning.js';
import{renderCapabilityQuiz}from'https://dmdgkjksouhhsuojthav.supabase.co/functions/v1/hlo-app?asset=capability.js';
import{renderMissions,renderLabs,renderResearch,renderSources}from'https://dmdgkjksouhhsuojthav.supabase.co/functions/v1/hlo-app?asset=operations.js';
import{renderFrontier,renderOpportunities,renderLeverage}from'https://dmdgkjksouhhsuojthav.supabase.co/functions/v1/hlo-app?asset=strategy.js';
import{renderOwner,renderEmpire,renderAccount}from'https://dmdgkjksouhhsuojthav.supabase.co/functions/v1/hlo-app?asset=owner.js';
import{initExperience}from'https://dmdgkjksouhhsuojthav.supabase.co/functions/v1/hlo-app?asset=experience-v2.js';

function ensureMobileStyles(){if(document.getElementById('hloMobileFixes'))return;const l=document.createElement('link');l.id='hloMobileFixes';l.rel='stylesheet';l.href='https://dmdgkjksouhhsuojthav.supabase.co/functions/v1/hlo-app?asset=mobile-fixes.css';document.head.appendChild(l)}
function ensureSection(id){if(document.getElementById(id))return;const s=document.createElement('section');s.id=id;s.className='view';document.querySelector('main.main')?.appendChild(s)}
function addButton(parent,id,label,before=null,cls=''){if(!parent||document.querySelector(`[data-view="${id}"]`))return;const b=document.createElement('button');b.dataset.view=id;b.textContent=label;if(cls)b.className=cls;before?parent.insertBefore(b,before):parent.appendChild(b)}
function ensureArchitecture(){
 ensureMobileStyles();
 document.title='Human OS — Stay Ahead of AI, Automation & Robotics';const meta=document.querySelector('meta[name="description"]');if(meta)meta.content='Human OS teaches you to understand, anticipate and capitalize on AI, automation and robotics through adaptive learning, frontier intelligence, applied experiments and durable ownership.';
 document.querySelectorAll('[data-view="career"],[data-view="trading"],#career,#trading').forEach(x=>x.remove());document.querySelectorAll('.subfolder').forEach(x=>{if(!x.querySelector('[data-view]'))x.remove()});
 ['frontier','opportunities','leverage','empire'].forEach(ensureSection);
 const researchBtn=document.querySelector('[data-view="research"]');const intel=researchBtn?.parentElement;if(intel){addButton(intel,'frontier','Frontier Radar',researchBtn,'nav-feature');addButton(intel,'opportunities','Opportunity Engine',researchBtn);addButton(intel,'leverage','Leverage Balance Sheet',researchBtn)}
 const nexus=document.querySelector('[data-view="nexus"]');const ownerItems=nexus?.parentElement;if(ownerItems)addButton(ownerItems,'empire','Empire Capstone',null,'owner-only');
 const hero=document.querySelector('.marketing-hero');if(hero){const eye=hero.querySelector('.eyebrow');if(eye)eye.textContent='AI-era leverage and opportunity education';const p=hero.querySelector('p');if(p)p.textContent='Human OS teaches you how to understand, anticipate and capitalize on artificial intelligence, automation and robotics. Build the knowledge, judgment, systems capability and ownership required to become more valuable as machine capability rises.'}
 const curr=document.querySelector('#curriculum .eyebrow');if(curr)curr.textContent='Universal AI-era foundation';
}
function renderMissionsClean(){renderMissions();document.querySelectorAll('#missionTrack option').forEach(o=>{if(['Career','Trading'].includes(o.value||o.textContent))o.remove()})}
const renders={dashboard:renderDashboard,personalize:renderPath,academy:renderAcademy,tutor:renderTutor,quiz:renderCapabilityQuiz,mastery:renderMastery,missions:renderMissionsClean,labs:renderLabs,frontier:renderFrontier,opportunities:renderOpportunities,leverage:renderLeverage,research:renderResearch,sources:renderSources,account:renderAccount,nexus:renderOwner,statecraft:renderOwner,empire:renderEmpire};
function saveLocation(){try{const active=document.querySelector('.view.active')?.id||'dashboard';sessionStorage.setItem('hlo:lastView',active);sessionStorage.setItem('hlo:lastScrollY',String(Math.max(0,Math.round(window.scrollY||0))));if(active==='academy'&&S.module?.id)sessionStorage.setItem('hlo:lastModule',S.module.id)}catch{}}
async function restoreLocation(){let view='dashboard',moduleId=null,scrollY=0;try{const hash=location.hash.slice(1);view=(hash&&document.getElementById(hash))?hash:(sessionStorage.getItem('hlo:lastView')||'dashboard');moduleId=sessionStorage.getItem('hlo:lastModule');scrollY=Number(sessionStorage.getItem('hlo:lastScrollY'))||0}catch{}if(['nexus','statecraft','empire'].includes(view)&&!S.owner)view='dashboard';if(!document.getElementById(view))view='dashboard';go(view);if(view==='academy'&&moduleId&&S.modules.some(m=>m.id===moduleId)){await openModule(moduleId)}setTimeout(()=>window.scrollTo({top:scrollY,behavior:'auto'}),80)}
async function boot(){ensureArchitecture();initNav();initAuth();await loadModules();await bootSession();if(S.user){await loadCloud();openAfterAuth()}await renderOwner();renderDashboard();renderPath();renderAcademy();renderMastery();renderResearch();renderSources();renderAccount();initExperience();window.addEventListener('hlo:view',e=>{const id=e.detail.id;if(['nexus','statecraft','empire'].includes(id)&&!S.owner){go('dashboard');return}const fn=renders[id];if(fn)fn()});window.addEventListener('hlo:go',e=>go(e.detail.id));window.addEventListener('pagehide',saveLocation);await restoreLocation()}
boot().catch(e=>{console.error(e);document.body.insertAdjacentHTML('beforeend',`<div class="startup-error" role="alert"><b>Human OS could not finish loading.</b><br>${String(e.message||e)}<br><small>Your saved account data has not been changed.</small></div>`)})
