import{sb,S,$,toast,go,track,CFG}from'https://dmdgkjksouhhsuojthav.supabase.co/functions/v1/hlo-app?asset=core.js';
let mode='login';
const POLICY={terms:`Human OS is an educational learning platform. It does not provide accredited credentials or guarantee employment, business, investment, trading, health, legal or financial outcomes. You remain responsible for consequential decisions, source verification and how you apply the material. Do not upload information you are not authorized to share. Human OS features may change as the product develops.`,privacy:`Human OS stores the account and learning information needed to provide the service: profile preferences, curriculum, lesson progress, quiz results, missions, lab drafts, notes, saved sources and Tutor history. Personalization uses information you explicitly provide plus your learning activity. Tutor questions may be processed by configured AI providers to generate instructional responses. Human OS does not use editable profile fields to grant owner/admin authorization. You can export learning data, clear learning history and request account deletion from Account settings.`};
function setMode(m){mode=m;const signup=m==='signup';$('#nameWrap').style.display=signup?'grid':'none';$('#termsWrap')?.classList.toggle('hidden',!signup);$('#authSubmit').textContent=signup?'Create free account':'Sign in';$('#authHeading').textContent=signup?'Build your Human OS':'Welcome back';$('#authIntro').textContent=signup?'Create a free account to save your path, progress, missions and Tutor history across devices.':'Sign in to continue your curriculum, mastery, missions and Tutor history across devices.';$('#loginTab').classList.toggle('primary',!signup);$('#signupTab').classList.toggle('primary',signup);$('#authPassword').autocomplete=signup?'new-password':'current-password';$('#authMsg').textContent=signup?'Use at least 10 characters with a letter and a number. Human OS also checks new passwords against known breach data without sending your password to the breach service.':'Use your Human OS account credentials.'}
function openPanel(m='signup',source='unknown'){$('#authPanel').classList.remove('hidden');setMode(m);track('auth_opened',{mode:m,source}).catch(()=>{});if(m==='signup')track('signup_started',{source}).catch(()=>{});else track('login_started',{source}).catch(()=>{});setTimeout(()=>$('#authEmail')?.focus(),30)}function closePanel(){$('#authPanel').classList.add('hidden')}
export function initAuth(){setMode('login');track('marketing_viewed',{path:location.pathname}).catch(()=>{});$('#loginTab').onclick=()=>setMode('login');$('#signupTab').onclick=()=>setMode('signup');$('#closeAuth').onclick=closePanel;$('#authPanel').onclick=e=>{if(e.target.id==='authPanel')closePanel()};['marketingStart','heroStart','planFree','planPlus'].forEach(id=>$('#'+id)&&($('#'+id).onclick=()=>{track('cta_clicked',{id}).catch(()=>{});if(id==='planPlus')track('plan_interest',{plan:'Human OS+'}).catch(()=>{});openPanel('signup',id)}));['marketingSignIn','footerSignIn'].forEach(id=>$('#'+id)&&($('#'+id).onclick=()=>openPanel('login',id)));$('#marketingExplore').onclick=()=>openPreview('marketingExplore');$('#offlineBtn').onclick=()=>openPreview('offlineBtn');$('#authSubmit').onclick=submit;$('#forgotPassword').onclick=forgot;$('#togglePassword').onclick=()=>{const p=$('#authPassword'),show=p.type==='password';p.type=show?'text':'password';$('#togglePassword').textContent=show?'Hide':'Show'};injectPolicyLinks();detectOAuth();document.addEventListener('keydown',e=>{if(e.key==='Escape'){closePanel();closePolicy()}if(e.key==='Enter'&&!$('#authPanel').classList.contains('hidden')&&document.activeElement?.tagName!=='TEXTAREA')submit()})}
function injectPolicyLinks(){const wrap=$('#termsWrap');if(!wrap||$('#policyLinks'))return;const links=document.createElement('span');links.id='policyLinks';links.innerHTML=` <button type="button" class="link-button policy-link" data-policy="terms">Terms</button> · <button type="button" class="link-button policy-link" data-policy="privacy">Privacy</button>`;wrap.querySelector('span')?.appendChild(links);document.querySelectorAll('.policy-link').forEach(b=>b.onclick=e=>{e.preventDefault();showPolicy(b.dataset.policy)})}
function showPolicy(kind){closePolicy();const panel=document.createElement('div');panel.id='policyModal';panel.className='auth-panel';panel.style.zIndex='500';panel.innerHTML=`<div class="auth-box"><button id="closePolicy" class="auth-close" aria-label="Close">×</button><div class="eyebrow">Human OS ${kind==='terms'?'Terms':'Privacy Notice'}</div><h2>${kind==='terms'?'Use Human OS responsibly':'Your learning data stays under your control'}</h2><p class="muted" style="line-height:1.7">${POLICY[kind]}</p><button id="policyDone" class="btn primary">Done</button></div>`;document.body.appendChild(panel);$('#closePolicy').onclick=closePolicy;$('#policyDone').onclick=closePolicy;panel.onclick=e=>{if(e.target===panel)closePolicy()}}
function closePolicy(){document.getElementById('policyModal')?.remove()}
async function detectOAuth(){try{const r=await fetch(`${CFG.supabaseUrl}/auth/v1/settings`,{headers:{apikey:CFG.publishableKey}});if(!r.ok)return;const j=await r.json(),providers=[];if(j?.external?.google)providers.push(['google','Continue with Google']);if(j?.external?.apple)providers.push(['apple','Continue with Apple']);if(!providers.length)return;const host=document.createElement('div');host.id='oauthButtons';host.style.cssText='display:grid;gap:8px;margin:10px 0';host.innerHTML=providers.map(p=>`<button class="btn oauth-btn" data-provider="${p[0]}">${p[1]}</button>`).join('');$('#authSubmit').parentNode.insertBefore(host,$('#authSubmit'));host.querySelectorAll('.oauth-btn').forEach(b=>b.onclick=()=>oauth(b.dataset.provider))}catch{}}
async function oauth(provider){track('oauth_clicked',{provider}).catch(()=>{});msg(`Opening ${provider} sign in…`);const{error}=await sb.auth.signInWithOAuth({provider,options:{redirectTo:window.location.origin}});if(error)msg(friendly(error.message))}
function openPreview(source='guest'){$('#authPanel')?.classList.add('hidden');$('#authGate').classList.add('hidden');S.offline=true;$('#cloudStatus').textContent='Guest preview';$('#accountLabel').textContent='Guest preview';track('guest_preview_opened',{source}).catch(()=>{});go('academy');toast('Free lesson preview opened')}
export function openAfterAuth(){if(S.user){$('#authGate').classList.add('hidden');$('#authPanel')?.classList.add('hidden')}}
async function sha1(text){const data=new TextEncoder().encode(text),hash=await crypto.subtle.digest('SHA-1',data);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('').toUpperCase()}
export async function checkPasswordSafety(password){try{const hash=await sha1(password),prefix=hash.slice(0,5),suffix=hash.slice(5);const r=await fetch(`${CFG.supabaseUrl}/functions/v1/hlo-password-check?prefix=${prefix}`,{headers:{apikey:CFG.publishableKey}});if(!r.ok)return{ok:true,checked:false};const text=await r.text();const hit=text.split(/\r?\n/).find(line=>line.toUpperCase().startsWith(suffix+':'));if(hit){const count=Number(hit.split(':')[1])||1;return{ok:false,checked:true,count}}return{ok:true,checked:true,count:0}}catch{return{ok:true,checked:false}}}
async function submit(){const email=$('#authEmail').value.trim(),password=$('#authPassword').value,name=$('#authName').value.trim();if(!/^\S+@\S+\.\S+$/.test(email))return msg('Enter a valid email.');if(password.length<10||!/[A-Za-z]/.test(password)||!/[0-9]/.test(password))return msg('Use at least 10 characters with at least one letter and one number.');if(mode==='signup'&&!$('#acceptTerms')?.checked)return msg('Review and accept the Terms and Privacy notice to create the account.');const btn=$('#authSubmit');btn.disabled=true;try{if(mode==='login'){track('login_started',{source:'submit'}).catch(()=>{});msg('Signing in…');const{data,error}=await sb.auth.signInWithPassword({email,password});if(error)return msg(friendly(error.message));if(data.session){await track('login_completed');msg('Signed in. Loading your Human OS…');setTimeout(()=>location.reload(),200)}}else{track('signup_started',{source:'submit'}).catch(()=>{});msg('Checking password safety…');const safe=await checkPasswordSafety(password);if(!safe.ok)return msg(`Choose a different password. This password appears in known breach data${safe.count?` (${safe.count.toLocaleString()} occurrences)`:''}. Human OS has not sent your password to the breach database.`);msg('Creating your account…');const{data,error}=await sb.auth.signUp({email,password,options:{data:{display_name:name||email.split('@')[0],human_os_terms_accepted_at:new Date().toISOString()},emailRedirectTo:window.location.origin}});if(error)return msg(friendly(error.message));await track('signup_completed',{session_created:!!data.session});if(data.session){msg('Account created. Loading your Human OS…');setTimeout(()=>location.reload(),200)}else msg('Check your email to confirm your account, then return here and sign in.')}}catch(e){msg('Authentication failed. '+friendly(e.message))}finally{btn.disabled=false}}
async function forgot(){const email=$('#authEmail').value.trim();if(!/^\S+@\S+\.\S+$/.test(email))return msg('Enter your account email first.');msg('Sending password reset…');const{error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+'/#account'});msg(error?friendly(error.message):'Password reset email sent. Open the link, then return to Human OS.')}
function friendly(t=''){if(/invalid login/i.test(t))return'Email or password is incorrect.';if(/already registered/i.test(t))return'This email already has an account. Sign in instead.';return t}
function msg(t){$('#authMsg').textContent=t}
