import{sb,S,$,toast,go,track}from'https://dmdgkjksouhhsuojthav.supabase.co/functions/v1/hlo-app?asset=core.js';
let mode='login';
function setMode(m){mode=m;const signup=m==='signup';$('#nameWrap').style.display=signup?'grid':'none';$('#termsWrap')?.classList.toggle('hidden',!signup);$('#authSubmit').textContent=signup?'Create free account':'Sign in';$('#authHeading').textContent=signup?'Build your Human OS':'Welcome back';$('#authIntro').textContent=signup?'Create a free account to save your path, progress, missions and Tutor history across devices.':'Sign in to continue your curriculum, mastery, missions and Tutor history across devices.';$('#loginTab').classList.toggle('primary',!signup);$('#signupTab').classList.toggle('primary',signup);$('#authPassword').autocomplete=signup?'new-password':'current-password';$('#authMsg').textContent=signup?'Use at least 8 characters. You can export or delete your learning data later from Account settings.':'Use your Human OS account credentials.'}
function openPanel(m='signup'){$('#authPanel').classList.remove('hidden');setMode(m);setTimeout(()=>$('#authEmail')?.focus(),30)}function closePanel(){$('#authPanel').classList.add('hidden')}
export function initAuth(){setMode('login');$('#loginTab').onclick=()=>setMode('login');$('#signupTab').onclick=()=>setMode('signup');$('#closeAuth').onclick=closePanel;$('#authPanel').onclick=e=>{if(e.target.id==='authPanel')closePanel()};['marketingStart','heroStart','planFree','planPlus'].forEach(id=>$('#'+id)&&($('#'+id).onclick=()=>openPanel('signup')));['marketingSignIn','footerSignIn'].forEach(id=>$('#'+id)&&($('#'+id).onclick=()=>openPanel('login')));$('#marketingExplore').onclick=()=>openPreview();$('#offlineBtn').onclick=()=>openPreview();$('#authSubmit').onclick=submit;$('#forgotPassword').onclick=forgot;$('#togglePassword').onclick=()=>{const p=$('#authPassword'),show=p.type==='password';p.type=show?'text':'password';$('#togglePassword').textContent=show?'Hide':'Show'};document.addEventListener('keydown',e=>{if(e.key==='Escape')closePanel();if(e.key==='Enter'&&!$('#authPanel').classList.contains('hidden')&&document.activeElement?.tagName!=='TEXTAREA')submit()})}
function openPreview(){$('#authPanel')?.classList.add('hidden');$('#authGate').classList.add('hidden');S.offline=true;$('#cloudStatus').textContent='Guest preview';$('#accountLabel').textContent='Guest preview';go('academy');toast('Free lesson preview opened')}
export function openAfterAuth(){if(S.user){$('#authGate').classList.add('hidden');$('#authPanel')?.classList.add('hidden')}}
async function submit(){const email=$('#authEmail').value.trim(),password=$('#authPassword').value,name=$('#authName').value.trim();if(!/^\S+@\S+\.\S+$/.test(email))return msg('Enter a valid email.');if(password.length<8)return msg('Use at least 8 characters.');if(mode==='signup'&&!$('#acceptTerms')?.checked)return msg('Confirm the Terms and Privacy notice to create the account.');const btn=$('#authSubmit');btn.disabled=true;try{if(mode==='login'){msg('Signing in…');const{data,error}=await sb.auth.signInWithPassword({email,password});if(error)return msg(friendly(error.message));if(data.session){msg('Signed in. Loading your Human OS…');await track('login_completed');setTimeout(()=>location.reload(),200)}}else{msg('Creating your account…');const{data,error}=await sb.auth.signUp({email,password,options:{data:{display_name:name||email.split('@')[0],human_os_terms_accepted_at:new Date().toISOString()},emailRedirectTo:window.location.origin}});if(error)return msg(friendly(error.message));if(data.session){msg('Account created. Loading your Human OS…');setTimeout(()=>location.reload(),200)}else msg('Check your email to confirm your account, then return here and sign in.')}}catch(e){msg('Authentication failed. '+friendly(e.message))}finally{btn.disabled=false}}
async function forgot(){const email=$('#authEmail').value.trim();if(!/^\S+@\S+\.\S+$/.test(email))return msg('Enter your account email first.');msg('Sending password reset…');const{error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+'/#account'});msg(error?friendly(error.message):'Password reset email sent. Open the link, then return to Human OS.')}
function friendly(t=''){if(/invalid login/i.test(t))return'Email or password is incorrect.';if(/already registered/i.test(t))return'This email already has an account. Sign in instead.';return t}
function msg(t){$('#authMsg').textContent=t}
