export const CFG={supabaseUrl:'https://dmdgkjksouhhsuojthav.supabase.co',publishableKey:'sb_publishable_-bZLK1vmL0eUMz65A6EUsw_I20LBq2B',assetBase:'__ASSET_BASE__'};
export const sb=window.supabase.createClient(CFG.supabaseUrl,CFG.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
export const S={session:null,user:null,owner:false,offline:false,profile:null,progress:[],quizAttempts:[],missions:[],certs:[],research:[],curriculum:null,questionBank:[],modules:[],module:null,labDrafts:[],moduleNotes:[],savedSources:[],settings:null,supportRequests:[]};
export const PUBLIC_CORE_IDS=['M01','M02','M03','M04','M05','M06','M07','M12','M13'];
export const PRIVATE_SPECIALIZATION_IDS=['M08','M09','M11'];
export const $=s=>document.querySelector(s);export const $$=s=>[...document.querySelectorAll(s)];
export function toast(msg){const el=$('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
export function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
export function coreModules(){return S.modules.filter(m=>PUBLIC_CORE_IDS.includes(m.id))}
export function privateModules(){return S.modules.filter(m=>PRIVATE_SPECIALIZATION_IDS.includes(m.id))}
export function currentView(){return document.querySelector('.view.active')?.id||'dashboard'}
export function anonymousId(){let id='';try{id=localStorage.getItem('hlo_anon_id')||'';if(!id){id=crypto.randomUUID?crypto.randomUUID():`anon-${Date.now()}-${Math.random().toString(36).slice(2)}`;localStorage.setItem('hlo_anon_id',id)}}catch{id=`anon-${Date.now()}-${Math.random().toString(36).slice(2)}`}return id}
const PUBLIC_EVENTS=new Set(['marketing_viewed','cta_clicked','guest_preview_opened','auth_opened','signup_started','signup_completed','login_started','login_completed','oauth_clicked','plan_interest','seo_route_viewed']);
export async function track(event_name,properties={}){try{if(S.user){await sb.from('hlo_events').insert({user_id:S.user.id,anonymous_id:anonymousId(),event_name,view_name:currentView(),properties});return}if(!PUBLIC_EVENTS.has(event_name))return;await fetch(`${CFG.supabaseUrl}/functions/v1/hlo-public-event`,{method:'POST',headers:{'Content-Type':'application/json',apikey:CFG.publishableKey},body:JSON.stringify({anonymous_id:anonymousId(),event_name,view_name:currentView(),properties})})}catch(e){console.warn('analytics',e)}}
export function go(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));const b=$(`[data-view="${id}"]`),title=b?.textContent?.trim()||id;$('#viewTitle')&&($('#viewTitle').textContent=title);$('#mobileView')&&($('#mobileView').textContent=title);const group=b?.closest('.nav-group')?.querySelector('.nav-head span')?.textContent||'Human OS';$('#viewEyebrow')&&($('#viewEyebrow').textContent=group);history.replaceState(null,'',`#${id}`);document.body.classList.remove('menu-open');$('#mobileBackdrop')?.classList.add('hidden');window.scrollTo({top:0,behavior:'smooth'});window.dispatchEvent(new CustomEvent('hlo:view',{detail:{id}}));track('view_opened',{id}).catch(()=>{})}
export function pct(n,d){return d?Math.round(n/d*100):0}export function bestQuiz(){return Math.max(0,...S.quizAttempts.map(x=>Number(x.score)||0))}
export function completedLessons(){return new Set(S.progress.filter(x=>['completed','mastered'].includes(x.status)).map(x=>x.lesson_id))}
export function masteredLessons(){return new Set(S.progress.filter(x=>x.status==='mastered'||Number(x.mastery_score)>=85).map(x=>x.lesson_id))}
export function nextRecommendation(){const done=completedLessons(),mods=coreModules();if(!S.curriculum)return{type:'BUILD',title:'Build your personal path',reason:'Answer the onboarding questions so Human OS can connect the universal foundation to your actual goal.',view:'personalize'};const first=mods.find(m=>!done.has(m.id));if(first)return{type:'LEARN',title:first.title,reason:'Continue the durable foundation before adding more complexity.',view:'academy',module:first.id};const active=S.missions.find(m=>m.status==='active'||m.status==='in_progress');if(active)return{type:'BUILD',title:active.title||'Finish your active mission',reason:'Turn knowledge into evidence before adding another project.',view:'missions'};if(bestQuiz()<80)return{type:'TEST',title:'Run an adaptive knowledge check',reason:'Use retrieval and scenario questions to expose weak concepts.',view:'quiz'};return{type:'PRACTICE',title:'Apply your path to a real project',reason:'Mastery should end in a useful artifact, not just course completion.',view:'missions'}}
export function initNav(){$$('.nav-head').forEach(b=>b.onclick=()=>b.parentElement.classList.toggle('open'));$$('.subhead').forEach(b=>b.onclick=()=>b.parentElement.classList.toggle('open'));$$('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));$('#signOutBtn').onclick=async()=>{await track('signed_out');await sb.auth.signOut();location.href=location.origin};$('#mobileMenu')&&( $('#mobileMenu').onclick=()=>{document.body.classList.toggle('menu-open');$('#mobileBackdrop')?.classList.toggle('hidden',!document.body.classList.contains('menu-open'))});$('#mobileBackdrop')&&( $('#mobileBackdrop').onclick=()=>{document.body.classList.remove('menu-open');$('#mobileBackdrop').classList.add('hidden')})}
export async function loadCloud(){if(!S.user)return;const uid=S.user.id;const queries=await Promise.all([
 sb.from('hlo_profiles').select('*').eq('user_id',uid).maybeSingle(),sb.from('hlo_lesson_progress').select('*').eq('user_id',uid),sb.from('hlo_quiz_attempts').select('*').eq('user_id',uid).order('created_at',{ascending:false}).limit(30),sb.from('hlo_missions').select('*').eq('user_id',uid).order('created_at',{ascending:false}),sb.from('hlo_certificates').select('*').eq('user_id',uid),sb.from('hlo_research_items').select('*').order('published_at',{ascending:false}).limit(80),sb.from('hlo_question_bank').select('*').eq('active',true),sb.from('hlo_custom_curricula').select('*').eq('user_id',uid).eq('status','active').order('created_at',{ascending:false}).limit(1).maybeSingle(),sb.from('hlo_owner_users').select('user_id').eq('user_id',uid).maybeSingle(),sb.from('hlo_lab_drafts').select('*').eq('user_id',uid),sb.from('hlo_module_notes').select('*').eq('user_id',uid),sb.from('hlo_saved_sources').select('*').eq('user_id',uid).order('created_at',{ascending:false}),sb.from('hlo_user_settings').select('*').eq('user_id',uid).maybeSingle(),sb.from('hlo_support_requests').select('*').eq('user_id',uid).order('created_at',{ascending:false}).limit(10)]);
 const [p,prog,qa,mis,cert,res,qb,cur,own,labs,notes,saved,settings,support]=queries;S.profile=p.data;S.progress=prog.data||[];S.quizAttempts=qa.data||[];S.missions=mis.data||[];S.certs=cert.data||[];S.research=res.data||[];S.questionBank=qb.data||[];S.curriculum=cur.data?.curriculum||null;S.owner=!!own.data;S.labDrafts=labs.data||[];S.moduleNotes=notes.data||[];S.savedSources=saved.data||[];S.settings=settings.data||null;S.supportRequests=support.data||[];document.body.classList.toggle('owner',S.owner);$('#cloudStatus')&&($('#cloudStatus').textContent='Cloud synced');$('#statusDot')?.classList.add('ok');$('#accountLabel')&&($('#accountLabel').textContent=S.owner?'Owner account':(S.user.email||'Signed in'));$('#signOutBtn')?.classList.remove('hidden')}
export async function loadModules(){const parts=await Promise.all([1,2,3,4,5].map(i=>fetch(`${CFG.assetBase}?asset=modules-${String(i).padStart(2,'0')}.json`,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(`Module asset ${i} failed: ${r.status}`);return r.json()})));S.modules=parts.flat()}
export async function markModule(id,score=null){if(!S.user){toast('Create a free account to save progress.');return}const old=S.progress.find(x=>x.lesson_id===id);const mastery=Math.max(Number(old?.mastery_score)||0,Number(score)||0);const status=mastery>=85?'mastered':'completed';const row={user_id:S.user.id,lesson_id:id,status,mastery_score:mastery,attempts:(old?.attempts||0)+(score!==null?1:0),started_at:old?.started_at||new Date().toISOString(),completed_at:old?.completed_at||new Date().toISOString(),updated_at:new Date().toISOString()};const {error}=await sb.from('hlo_lesson_progress').upsert(row,{onConflict:'user_id,lesson_id'});if(error)throw error;S.progress=S.progress.filter(x=>x.lesson_id!==id).concat(row);await track('module_progress_saved',{lesson_id:id,status,mastery_score:mastery});toast(status==='mastered'?'Module mastered':'Progress saved')}
export async function bootSession(){const {data,error}=await sb.auth.getSession();if(error)throw error;S.session=data.session;S.user=data.session?.user||null;return S.user}
setTimeout(()=>import(`${CFG.assetBase}?asset=experience.js`).catch(e=>console.warn('experience enhancements',e)),0);
