import{S,$,sb,esc,toast,track,coreModules}from'https://dmdgkjksouhhsuojthav.supabase.co/functions/v1/hlo-app?asset=core.js';
const CANON=[
 ['Stanford HAI','AI capability, adoption and economic research','Research','https://hai.stanford.edu/ai-index'],
 ['PwC AI Jobs Barometer','AI skills, labor demand and wage patterns','Research','https://www.pwc.com/gx/en/issues/artificial-intelligence/job-barometer.html'],
 ['World Economic Forum','Future of Jobs and skill change','Report','https://www.weforum.org/publications/the-future-of-jobs-report-2025/'],
 ['NIST AI RMF','Governance, mapping, measurement and management','Standard','https://www.nist.gov/itl/ai-risk-management-framework'],
 ['Anthropic Economic Index','Task use, augmentation and labor patterns','Research','https://www.anthropic.com/economic-index'],
 ['McKinsey Global Institute','Workflow redesign, agents and automation economics','Research','https://www.mckinsey.com/mgi'],
 ['International Federation of Robotics','Industrial robotics and physical automation','Industry data','https://ifr.org/worldrobotics'],
 ['International Energy Agency','Data-center power and infrastructure constraints','Research','https://www.iea.org/reports/energy-and-ai']
];
const state={q:'',topic:'all',type:'all',age:'all',savedQ:''};
function evidenceType(r){const s=`${r.source_name||''} ${r.title||''}`.toLowerCase();if(/nist|standard|framework/.test(s))return'Standard';if(/stanford|pwc|anthropic|institute|research|study/.test(s))return'Research';if(/world economic forum|report/.test(s))return'Report';if(/cftc|government|department|agency/.test(s))return'Government';return'Industry data'}
function relatedModules(r){const text=`${r.topic||''} ${r.title||''} ${r.summary||''}`.toLowerCase(),mods=coreModules();return mods.map(m=>({id:m.id,score:[m.title,m.summary,...(m.objectives||[])].join(' ').toLowerCase().split(/\W+/).filter(w=>w.length>4).reduce((n,w)=>n+(text.includes(w)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,3).map(x=>x.id)}
function sourceKey(r){return `research:${r.id||btoa(unescape(encodeURIComponent(r.source_url||r.title||'source'))).slice(0,24)}`}
function saved(key){return S.savedSources.find(x=>x.source_key===key)}
function ageOk(r){if(state.age==='all'||!r.published_at)return true;const days=(Date.now()-new Date(r.published_at).getTime())/86400000;return state.age==='30'?days<=30:state.age==='365'?days<=365:true}
export function renderEnhancedResearch(){const root=$('#research');if(!root)return;const topics=['all',...[...new Set((S.research||[]).map(r=>r.topic).filter(Boolean))].sort()],types=['all','Research','Report','Standard','Government','Industry data'];const items=(S.research||[]).filter(r=>(state.topic==='all'||r.topic===state.topic)&&(state.type==='all'||evidenceType(r)===state.type)&&ageOk(r)&&(!state.q||`${r.topic} ${r.title} ${r.summary} ${r.source_name}`.toLowerCase().includes(state.q.toLowerCase())));root.innerHTML=`<div class="card"><div class="eyebrow">Research Updates</div><h2>Dated evidence that can change the curriculum</h2><p class="muted">Filter by topic, evidence type and date. Save a source to your library when it materially supports a lesson, decision or mission.</p><div class="toolbar"><input id="rxQ" placeholder="Search source or claim…" value="${esc(state.q)}" style="min-width:220px;flex:1;background:#0d1115;border:1px solid var(--line);color:var(--text);border-radius:9px;padding:10px"><select id="rxTopic">${topics.map(x=>`<option value="${esc(x)}">${esc(x==='all'?'All topics':x)}</option>`).join('')}</select><select id="rxType">${types.map(x=>`<option value="${esc(x)}">${esc(x==='all'?'All evidence':x)}</option>`).join('')}</select><select id="rxAge"><option value="all">Any date</option><option value="30">Last 30 days</option><option value="365">Last year</option></select></div></div><div class="card" style="margin-top:14px">${items.length?items.slice(0,50).map(r=>researchCard(r)).join(''):'<div class="empty">No research items match these filters.</div>'}</div>`;$('#rxTopic').value=state.topic;$('#rxType').value=state.type;$('#rxAge').value=state.age;$('#rxQ').oninput=e=>{state.q=e.target.value;renderEnhancedResearch()};$('#rxTopic').onchange=e=>{state.topic=e.target.value;renderEnhancedResearch()};$('#rxType').onchange=e=>{state.type=e.target.value;renderEnhancedResearch()};$('#rxAge').onchange=e=>{state.age=e.target.value;renderEnhancedResearch()};root.querySelectorAll('[data-save-source]').forEach(b=>b.onclick=()=>toggleSave(b.dataset.saveSource))}
function researchCard(r){const key=sourceKey(r),rel=relatedModules(r),isSaved=!!saved(key);return `<div class="research-item"><div class="eyebrow">${esc(r.topic||'Research')} · ${esc(evidenceType(r))} · ${r.published_at?new Date(r.published_at).toLocaleDateString():'Undated'}</div><b>${esc(r.title||'Untitled')}</b><p class="muted small">${esc(r.summary||'')}</p>${rel.length?`<div class="tag-cloud">${rel.map(x=>`<span>Related: ${esc(x)}</span>`).join('')}</div>`:''}<div class="toolbar">${r.source_url?`<a class="btn" href="${esc(r.source_url)}" target="_blank" rel="noopener">Open ${esc(r.source_name||'source')}</a>`:''}<button class="btn ghost" data-save-source="${esc(key)}">${isSaved?'Remove saved source':'Save to library'}</button></div></div>`}
async function toggleSave(key){if(!S.user)return toast('Create a free account to save research.');const item=(S.research||[]).find(r=>sourceKey(r)===key),existing=saved(key);if(existing){const{error}=await sb.from('hlo_saved_sources').delete().eq('id',existing.id);if(error)return toast(error.message);S.savedSources=S.savedSources.filter(x=>x.id!==existing.id);await track('research_source_removed',{source_key:key});toast('Removed from saved sources')}else if(item){const row={user_id:S.user.id,source_key:key,title:item.title||item.source_name||'Saved source',url:item.source_url||'',source_name:item.source_name||null,topic:item.topic||null,published_at:item.published_at||null,evidence_type:evidenceType(item),related_module_ids:relatedModules(item),notes:''};const{data,error}=await sb.from('hlo_saved_sources').upsert(row,{onConflict:'user_id,source_key'}).select().single();if(error)return toast(error.message);S.savedSources=[data,...S.savedSources.filter(x=>x.source_key!==key)];await track('research_source_saved',{source_key:key,topic:item.topic,evidence_type:row.evidence_type});toast('Source saved')}renderEnhancedResearch()}
export function renderEnhancedSources(){const root=$('#sources');if(!root)return;const savedItems=(S.savedSources||[]).filter(x=>!state.savedQ||`${x.title} ${x.source_name} ${x.topic} ${x.evidence_type} ${(x.related_module_ids||[]).join(' ')}`.toLowerCase().includes(state.savedQ.toLowerCase()));root.innerHTML=`<div class="card"><div class="eyebrow">Research Library</div><h2>Canonical and saved evidence</h2><p class="muted">Use primary or high-authority sources for claims that matter. Saved items preserve the evidence type and the Human OS lessons they most closely support.</p><input id="savedQ" placeholder="Search saved sources, topics or modules…" value="${esc(state.savedQ)}" style="width:100%;max-width:560px;background:#0d1115;border:1px solid var(--line);color:var(--text);border-radius:9px;padding:10px"></div><div class="card" style="margin-top:14px"><div class="eyebrow">Saved by you</div>${S.user?(savedItems.length?savedItems.map(savedCard).join(''):'<div class="empty">No saved sources yet. Save useful evidence from Research Updates.</div>'):'<div class="empty">Create a free account to save and annotate sources.</div>'}</div><div class="grid two" style="margin-top:14px">${CANON.map(x=>`<div class="card"><div class="eyebrow">${esc(x[2])}</div><h3>${esc(x[0])}</h3><p class="muted">${esc(x[1])}</p><a class="btn" href="${esc(x[3])}" target="_blank" rel="noopener">Open source</a></div>`).join('')}</div>`;$('#savedQ').oninput=e=>{state.savedQ=e.target.value;renderEnhancedSources()};root.querySelectorAll('[data-source-note]').forEach(b=>b.onclick=()=>saveSourceNote(b.dataset.sourceNote));root.querySelectorAll('[data-source-remove]').forEach(b=>b.onclick=()=>removeSaved(b.dataset.sourceRemove))}
function savedCard(x){return `<div class="research-item"><div class="eyebrow">${esc(x.topic||'Saved')} · ${esc(x.evidence_type||'Evidence')} ${x.published_at?'· '+new Date(x.published_at).toLocaleDateString():''}</div><b>${esc(x.title)}</b><div class="tag-cloud">${(x.related_module_ids||[]).map(m=>`<span>${esc(m)}</span>`).join('')}</div><div class="field"><textarea id="sourceNote-${x.id}" placeholder="Why does this source matter? What claim does it support?">${esc(x.notes||'')}</textarea></div><div class="toolbar"><a class="btn" href="${esc(x.url)}" target="_blank" rel="noopener">Open source</a><button class="btn" data-source-note="${x.id}">Save note</button><button class="btn ghost" data-source-remove="${x.id}">Remove</button></div></div>`}
async function saveSourceNote(id){const item=S.savedSources.find(x=>String(x.id)===String(id)),notes=$(`#sourceNote-${CSS.escape(id)}`)?.value.trim()||'';if(!item)return;const{data,error}=await sb.from('hlo_saved_sources').update({notes}).eq('id',id).select().single();if(error)return toast(error.message);S.savedSources=S.savedSources.map(x=>x.id===data.id?data:x);await track('saved_source_note_updated',{source_key:data.source_key});toast('Source note saved')}
async function removeSaved(id){const item=S.savedSources.find(x=>String(x.id)===String(id));if(!item)return;const{error}=await sb.from('hlo_saved_sources').delete().eq('id',id);if(error)return toast(error.message);S.savedSources=S.savedSources.filter(x=>String(x.id)!==String(id));await track('research_source_removed',{source_key:item.source_key});renderEnhancedSources();toast('Saved source removed')}
const PUBLIC_PAGES={
 'ai-agents':{title:'AI Agents: What They Are and When to Use Them',eyebrow:'Human OS Learning Guide',body:'An AI agent is a system that can pursue a bounded objective across multiple steps using models, tools, memory or external systems. The useful question is not whether something can be made agentic; it is whether the task benefits from flexible reasoning enough to justify the added uncertainty, cost and control requirements.',points:['Use deterministic automation when the steps and rules are stable.','Use agents when the workflow requires context-sensitive decisions or tool selection.','Define tools, permissions, stop conditions, output schemas and human approval points before increasing autonomy.','Evaluate agents with realistic failures, not only happy-path demos.']},
 'human-advantage':{title:'The Human Advantage in an AI-Rich World',eyebrow:'Human OS Learning Guide',body:'As machine capability becomes cheaper and more abundant, durable human value shifts toward problem selection, judgment, trust, taste, verification, relationship quality, accountability and ownership. Human OS is designed to develop those capabilities alongside AI fluency.',points:['Learn enough AI to direct and evaluate it.','Keep consequential judgment and accountability explicit.','Turn repeated work into systems, evidence, distribution or owned assets.','Measure capability by what you can explain, build, verify and improve.']},
 'career':{title:'Build Career Leverage With AI',eyebrow:'Human OS Path',body:'The career path combines AI fluency with proof of capability. Instead of collecting prompts or certificates, learners map target-role requirements to verified evidence, identify gaps, build projects and practice human skills that remain valuable when execution becomes easier to automate.',points:['Map job requirements to real evidence and gaps.','Build small portfolio artifacts tied to actual workflows.','Use AI for preparation and analysis without fabricating experience.','Strengthen communication, judgment and relationship skills alongside technical leverage.']},
 'entrepreneur':{title:'Build an AI-Leveraged Business',eyebrow:'Human OS Path',body:'Entrepreneurs should use AI to increase productive capacity, not to create opaque complexity. Human OS teaches workflow decomposition, agent boundaries, verification, measurement and ownership so AI becomes part of a repeatable operating system.',points:['Start from a customer or operational bottleneck.','Document the manual process before automating it.','Use bounded AI where flexibility creates real value.','Measure baseline, change, outcome and remaining human work.']},
 'about':{title:'About Human OS',eyebrow:'Human OS',body:'Human OS is a personalized learning operating system built on the Human Leverage Method. It combines a universal AI foundation, personalized paths, an adaptive Tutor, practical missions, labs, evidence-based mastery and source-backed research.',points:['Education, not accredited credentialing.','Personalization from explicit inputs and learning activity.','Human judgment remains authoritative for consequential decisions.','Learners can export, clear or delete their data.']},
 'terms':{title:'Human OS Terms Summary',eyebrow:'Legal',body:'Human OS is provided for education and capability-building. It does not guarantee employment, business performance, financial returns, health outcomes or other professional results. Users are responsible for source verification, lawful use and consequential decisions.',points:['Do not upload information you are not authorized to share.','Do not use Human OS as a substitute for licensed professional advice.','Features and curricula may change as the product develops.','Use of the service is subject to responsible and lawful behavior.']},
 'privacy':{title:'Human OS Privacy Summary',eyebrow:'Privacy',body:'Human OS stores account and learning information needed to personalize the service and sync progress. Personalization is based on explicit inputs plus learning activity, not hidden personality labels. Tutor prompts may be processed by configured AI providers.',points:['Export your Human OS data from Account settings.','Clear learning history without deleting your login.','Delete the account and linked learner records permanently.','Editable profile fields do not grant privileged authorization.']}
};
function publicPage(){const key=new URLSearchParams(location.search).get('page');return key&&PUBLIC_PAGES[key]?[key,PUBLIC_PAGES[key]]:null}
function renderPublicPage(){const found=publicPage();if(!found)return false;const[key,p]=found,gate=$('#authGate');if(!gate)return false;const main=gate.querySelector('.marketing-main');if(!main)return false;main.innerHTML=`<section class="marketing-section" style="padding-top:70px"><div class="eyebrow">${esc(p.eyebrow)}</div><h1>${esc(p.title)}</h1><p style="max-width:760px;font-size:1.08rem;line-height:1.8">${esc(p.body)}</p><div class="grid two" style="margin-top:22px">${p.points.map((x,i)=>`<div class="card"><div class="step-num">0${i+1}</div><p>${esc(x)}</p></div>`).join('')}</div><div class="toolbar" style="margin-top:22px"><a class="btn primary" href="/">Explore Human OS</a><button id="publicStart" class="btn">Build My Path</button></div></section>`;$('#publicStart')?.addEventListener('click',()=>document.getElementById('marketingStart')?.click());document.title=`${p.title} — Human OS`;let d=document.querySelector('meta[name="description"]');if(d)d.setAttribute('content',p.body.slice(0,155));track('seo_route_viewed',{page:key}).catch(()=>{});return true}
function enhanceMarketingFooter(){const foot=document.querySelector('.marketing-footer>div:last-child');if(!foot||document.getElementById('publicFooterLinks'))return;const span=document.createElement('span');span.id='publicFooterLinks';span.innerHTML=`<a href="/?page=about">About</a><a href="/?page=ai-agents">AI Agents</a><a href="/?page=human-advantage">Human Advantage</a><a href="/?page=career">Career Path</a><a href="/?page=entrepreneur">Entrepreneur Path</a><a href="/?page=terms">Terms</a><a href="/?page=privacy">Privacy</a>`;span.style.display='contents';foot.prepend(span)}
window.addEventListener('hlo:view',e=>{if(e.detail?.id==='research')setTimeout(renderEnhancedResearch,45);if(e.detail?.id==='sources')setTimeout(renderEnhancedSources,45)});setTimeout(()=>{enhanceMarketingFooter();renderPublicPage();if(document.querySelector('#research.view.active'))renderEnhancedResearch();if(document.querySelector('#sources.view.active'))renderEnhancedSources()},180);
