import{S,$,sb,esc,toast}from'https://dmdgkjksouhhsuojthav.supabase.co/functions/v1/hlo-app?asset=core.js';
export function renderOwner(){
 const privateView=(id,label,body,items)=>{$(`#${id}`).innerHTML=`<div class="card"><div class="eyebrow">Private Studio · Owner only</div><h2>${label}</h2><p class="muted">${body}</p></div><div class="grid two" style="margin-top:14px">${items.map(x=>`<div class="card"><h3>${x[0]}</h3><p class="muted">${x[1]}</p></div>`).join('')}</div>`};
 privateView('nexus','Nexus Intelligence','Your private applied-learning track for diagnosing, designing, implementing and measuring AI systems for SMBs.',[['Diagnosis','Current state → desired state → gap → opportunity register.'],['Architecture','Manual SOP first; bounded agents, deterministic automation, human gates and rollback.'],['Proof','Baseline ledger, assumptions, change log, test/UAT record and measurement ledger.'],['Business leverage','Productize repeated delivery without fabricating ROI, testimonials or capability.']]);
 privateView('statecraft','Statecraft','Your private applied-learning track for human development, Reality Engineering, content and product systems.',[['Method','Current State → Gap → Desired State → experiment → evidence → recalibration.'],['Personalization','Explicit, consented memory with correction, export and delete.'],['Content','Canonical source lineage, videos when instructionally useful, human review for claims.'],['Human premium','Meaning, relationships, lived practice, judgment and identity remain human responsibilities.']]);
 privateView('career','Career','Your private AI-augmented career system. AI prepares; verified facts and human relationship decisions remain authoritative.',[['Job intelligence','Discover, deduplicate and score roles against real constraints.'],['Truth system','Requirement → evidence → gap mapping; no invented metrics or experience.'],['Proof portfolio','Turn domain work and AI projects into demonstrable artifacts.'],['Interview/relationship','Research, mock interviews, contextual follow-up and negotiation preparation.']]);
 privateView('trading','Trading','Your private research and process system. AI is a research assistant and analyst—not a live trading oracle.',[['Research','Hypotheses, code assistance, backtests, regime analysis and falsification.'],['Execution boundary','Zero AI-originated live order actions or autonomous risk overrides.'],['Journal','Structured setup/regime/risk/adherence/process data becomes proprietary evidence.'],['Operations','Automate logging, reconciliation, rule-state checks and reporting before chasing signal speed.']]);
}
export function renderAccount(){const p=S.profile||{};$('#account').innerHTML=`<div class="card"><div class="eyebrow">Account</div><h2>Profile & Preferences</h2><p class="muted">Your profile controls learning pace and goals. Authorization is not based on editable profile fields; owner access is stored separately.</p><div class="form-grid"><div class="field"><label>Display name</label><input id="displayName" value="${esc(p.display_name||S.user?.user_metadata?.display_name||'')}"></div><div class="field"><label>Weekly learning hours</label><input id="learningHours" type="number" min="1" max="30" value="${p.weekly_learning_hours||5}"></div></div><div class="field" style="margin-top:10px"><label>Primary goal</label><textarea id="goalStatement">${esc(p.goal_statement||'')}</textarea></div><div class="toolbar"><button id="saveProfile" class="btn primary">Save profile</button>${S.owner?'<span class="pill">Owner account</span>':'<span class="pill">Learner account</span>'}</div></div>`;$('#saveProfile').onclick=save}
async function save(){if(!S.user)return toast('Sign in to save profile.');const row={user_id:S.user.id,display_name:$('#displayName').value.trim(),weekly_learning_hours:+$('#learningHours').value||5,goal_statement:$('#goalStatement').value.trim(),updated_at:new Date().toISOString()};const{data,error}=await sb.from('hlo_profiles').upsert(row,{onConflict:'user_id'}).select().single();if(error)return toast(error.message);S.profile=data;toast('Profile saved')}
