import{S,$,sb,esc,toast,go}from'https://dmdgkjksouhhsuojthav.supabase.co/functions/v1/hlo-app?asset=core.js';

const STAGES=['signal','implication','opportunity','capability','experiment','evidence','asset','decision'];
let frontier=[],opportunities=[],leverage=[];
const signed=()=>!!S.user;
const arr=v=>Array.isArray(v)?v:[];
const score=o=>Math.max(0,(+o.score_value||0)+(+o.score_fit||0)+(+o.score_timing||0)+(+o.score_control||0)-(+o.score_risk||0));
function empty(id,title,body){$(id).innerHTML=`<div class="card"><div class="eyebrow">${esc(title)}</div><h2>Sign in required</h2><p class="muted">${esc(body)}</p></div>`}

export async function renderFrontier(){
 const host=$('#frontier');if(!host)return;if(!signed())return empty('#frontier','Frontier Radar','Sign in to turn frontier signals into a persistent opportunity pipeline.');
 host.innerHTML='<div class="card muted">Loading verified frontier signals…</div>';
 const{data,error}=await sb.from('hlo_frontier_signals').select('*').order('importance',{ascending:false}).order('published_at',{ascending:false}).limit(40);
 if(error){host.innerHTML=`<div class="card"><h2>Frontier Radar unavailable</h2><p class="muted">${esc(error.message)}</p></div>`;return}frontier=data||[];
 host.innerHTML=`<div class="card"><div class="eyebrow">Frontier Intelligence Radar</div><h2>What changed → what becomes cheap → what becomes scarce → what should you do?</h2><p class="muted">Human OS does not treat news as knowledge. Each verified signal is translated into strategic implications, opportunity vectors and capabilities worth building. Forecasts remain scenarios, not guarantees.</p><div class="callout"><b>Permanent lens:</b> AI capability should increase your productive capacity, ownership and optionality. Capture value by augmenting, architecting, owning, distributing and allocating—without outsourcing judgment.</div></div>
 <div style="margin-top:14px">${frontier.length?frontier.map(r=>`<div class="card" style="margin-bottom:12px"><div class="account-row"><div><div class="eyebrow">${esc(r.topic)} · importance ${r.importance}/5 · confidence ${r.confidence}%</div><h3>${esc(r.title)}</h3></div>${r.verified?'<span class="pill">Verified</span>':''}</div><p class="muted">${esc(r.what_changed)}</p><div class="grid two"><div><div class="small muted">WHY IT MATTERS</div><p>${esc(r.why_it_matters)}</p><div class="small muted">BECOMING CHEAPER</div><p>${esc(r.becoming_cheaper||'No durable conclusion recorded yet.')}</p><div class="small muted">BECOMING SCARCER</div><p>${esc(r.becoming_scarcer||'No durable conclusion recorded yet.')}</p></div><div><div class="small muted">OPPORTUNITY VECTORS</div><ul>${arr(r.opportunity_vectors).map(x=>`<li>${esc(x)}</li>`).join('')||'<li>Continue observing before committing.</li>'}</ul><div class="small muted">CAPABILITIES TO BUILD</div><div>${arr(r.capabilities_to_build).map(x=>`<span class="pill">${esc(x)}</span>`).join('')}</div></div></div><div class="callout"><b>Action now:</b> ${esc(r.action_now)}</div><div class="toolbar"><button class="btn primary capture-signal" data-id="${r.id}">Capture opportunity</button>${r.source_url?`<a class="btn" href="${esc(r.source_url)}" target="_blank" rel="noopener">Primary source</a>`:''}</div></div>`).join(''):'<div class="empty">No frontier signals are loaded yet.</div>'}</div>`;
 host.querySelectorAll('.capture-signal').forEach(b=>b.onclick=()=>captureSignal(b.dataset.id));
}
async function captureSignal(id){const r=frontier.find(x=>x.id===id);if(!r)return;const row={user_id:S.user.id,signal_id:r.id,title:r.title,implication:r.why_it_matters||'',opportunity:arr(r.opportunity_vectors)[0]||'',capability_needed:arr(r.capabilities_to_build).join(', '),stage:'opportunity',score_value:3,score_fit:3,score_timing:3,score_control:3,score_risk:3,updated_at:new Date().toISOString()};const{data,error}=await sb.from('hlo_opportunities').insert(row).select().single();if(error)return toast(error.message);opportunities.unshift(data);toast('Opportunity captured');go('opportunities')}

export async function renderOpportunities(){
 const host=$('#opportunities');if(!host)return;if(!signed())return empty('#opportunities','Opportunity Capture Engine','Sign in to save and mature opportunity theses.');
 const [{data:o,error},{data:f}]=await Promise.all([sb.from('hlo_opportunities').select('*').eq('user_id',S.user.id).order('updated_at',{ascending:false}),sb.from('hlo_frontier_signals').select('id,title,topic').order('importance',{ascending:false})]);if(error){host.innerHTML=`<div class="card"><h2>Opportunity Engine unavailable</h2><p class="muted">${esc(error.message)}</p></div>`;return}opportunities=o||[];frontier=f||frontier;
 host.innerHTML=`<div class="card"><div class="eyebrow">Opportunity Capture Engine</div><h2>Signal → implication → opportunity → capability → experiment → evidence → asset → decision.</h2><p class="muted">Do not confuse an exciting trend with an opportunity you control. Every thesis should end in a bounded experiment, evidence and an explicit scale / hold / kill decision.</p></div>
 <div class="card" style="margin-top:14px"><input type="hidden" id="oppId"><div class="form-grid"><div class="field"><label>Frontier signal</label><select id="oppSignal"><option value="">Independent thesis</option>${frontier.map(x=>`<option value="${x.id}">${esc(x.topic)} · ${esc(x.title)}</option>`).join('')}</select></div><div class="field"><label>Opportunity title</label><input id="oppTitle" placeholder="A specific opportunity worth testing"></div><div class="field"><label>Implication</label><textarea id="oppImplication" placeholder="What does the signal change?"></textarea></div><div class="field"><label>Opportunity</label><textarea id="oppOpportunity" placeholder="Where can value be captured?"></textarea></div><div class="field"><label>Capability needed</label><textarea id="oppCapability" placeholder="What must you learn, build or access?"></textarea></div><div class="field"><label>Bounded experiment</label><textarea id="oppExperiment" placeholder="What can you test cheaply in 1–30 days?"></textarea></div><div class="field"><label>Success metric</label><input id="oppMetric" placeholder="What observable result changes the decision?"></div><div class="field"><label>Evidence / asset path</label><textarea id="oppEvidence" placeholder="Evidence collected, prototype, customer signal, artifact, dataset or IP created"></textarea></div></div><div class="grid three" style="margin-top:12px">${[['oppValue','Value'],['oppFit','Fit'],['oppTiming','Timing'],['oppControl','Control'],['oppRisk','Risk']].map(x=>`<div class="field"><label>${x[1]} 1–5</label><input id="${x[0]}" type="number" min="1" max="5" value="3"></div>`).join('')}</div><div class="toolbar" style="margin-top:14px"><button id="saveOpp" class="btn primary">Save opportunity</button><button id="clearOpp" class="btn ghost">Clear</button></div></div>
 <div style="margin-top:14px">${opportunities.length?opportunities.sort((a,b)=>score(b)-score(a)).map(x=>`<div class="card" style="margin-bottom:10px"><div class="account-row"><div><div class="eyebrow">${esc(x.stage)} · decision ${esc(x.decision)} · priority ${score(x)}/17</div><h3>${esc(x.title)}</h3></div><span class="pill">${esc(x.decision)}</span></div><p class="muted">${esc(x.opportunity||x.implication||'No thesis recorded yet.')}</p><div class="small"><b>Capability:</b> ${esc(x.capability_needed||'—')}<br><b>Experiment:</b> ${esc(x.experiment||'—')}<br><b>Evidence:</b> ${esc(x.evidence||'—')}</div><div class="toolbar" style="margin-top:12px"><button class="btn edit-opp" data-id="${x.id}">Edit</button><button class="btn advance-opp" data-id="${x.id}">Advance stage</button><button class="btn decide-opp" data-id="${x.id}" data-decision="scale">Scale</button><button class="btn decide-opp" data-id="${x.id}" data-decision="hold">Hold</button><button class="btn decide-opp" data-id="${x.id}" data-decision="kill">Kill</button></div></div>`).join(''):'<div class="empty">No opportunities captured yet. Start in Frontier Radar or create an independent thesis above.</div>'}</div>`;
 $('#saveOpp').onclick=saveOpportunity;$('#clearOpp').onclick=clearOpportunity;host.querySelectorAll('.edit-opp').forEach(b=>b.onclick=()=>editOpportunity(b.dataset.id));host.querySelectorAll('.advance-opp').forEach(b=>b.onclick=()=>advanceOpportunity(b.dataset.id));host.querySelectorAll('.decide-opp').forEach(b=>b.onclick=()=>decideOpportunity(b.dataset.id,b.dataset.decision));
}
function clearOpportunity(){['oppId','oppTitle','oppImplication','oppOpportunity','oppCapability','oppExperiment','oppMetric','oppEvidence'].forEach(id=>{const e=$('#'+id);if(e)e.value=''});if($('#oppSignal'))$('#oppSignal').value='';['oppValue','oppFit','oppTiming','oppControl','oppRisk'].forEach(id=>$('#'+id).value=3)}
function editOpportunity(id){const x=opportunities.find(o=>o.id===id);if(!x)return;$('#oppId').value=x.id;$('#oppSignal').value=x.signal_id||'';$('#oppTitle').value=x.title||'';$('#oppImplication').value=x.implication||'';$('#oppOpportunity').value=x.opportunity||'';$('#oppCapability').value=x.capability_needed||'';$('#oppExperiment').value=x.experiment||'';$('#oppMetric').value=x.success_metric||'';$('#oppEvidence').value=x.evidence||'';$('#oppValue').value=x.score_value||3;$('#oppFit').value=x.score_fit||3;$('#oppTiming').value=x.score_timing||3;$('#oppControl').value=x.score_control||3;$('#oppRisk').value=x.score_risk||3;window.scrollTo({top:0,behavior:'smooth'})}
async function saveOpportunity(){const id=$('#oppId').value,title=$('#oppTitle').value.trim();if(!title)return toast('Add an opportunity title.');const row={user_id:S.user.id,signal_id:$('#oppSignal').value||null,title,implication:$('#oppImplication').value.trim(),opportunity:$('#oppOpportunity').value.trim(),capability_needed:$('#oppCapability').value.trim(),experiment:$('#oppExperiment').value.trim(),success_metric:$('#oppMetric').value.trim(),evidence:$('#oppEvidence').value.trim(),score_value:+$('#oppValue').value||3,score_fit:+$('#oppFit').value||3,score_timing:+$('#oppTiming').value||3,score_control:+$('#oppControl').value||3,score_risk:+$('#oppRisk').value||3,updated_at:new Date().toISOString()};let q=id?sb.from('hlo_opportunities').update(row).eq('id',id).eq('user_id',S.user.id):sb.from('hlo_opportunities').insert({...row,stage:'signal'});const{error}=await q;if(error)return toast(error.message);toast(id?'Opportunity updated':'Opportunity captured');renderOpportunities()}
async function advanceOpportunity(id){const x=opportunities.find(o=>o.id===id);if(!x)return;const i=STAGES.indexOf(x.stage),stage=STAGES[Math.min(STAGES.length-1,i+1)];const{error}=await sb.from('hlo_opportunities').update({stage,updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',S.user.id);if(error)return toast(error.message);toast(`Advanced to ${stage}`);renderOpportunities()}
async function decideOpportunity(id,decision){const{error}=await sb.from('hlo_opportunities').update({decision,stage:'decision',updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',S.user.id);if(error)return toast(error.message);toast(`Decision saved: ${decision}`);renderOpportunities()}

export async function renderLeverage(){
 const host=$('#leverage');if(!host)return;if(!signed())return empty('#leverage','Personal Leverage Balance Sheet','Sign in to build a persistent evidence-backed leverage history.');
 const{data,error}=await sb.from('hlo_leverage_snapshots').select('*').eq('user_id',S.user.id).order('created_at',{ascending:false}).limit(12);if(error){host.innerHTML=`<div class="card"><h2>Leverage Balance Sheet unavailable</h2><p class="muted">${esc(error.message)}</p></div>`;return}leverage=data||[];const latest=leverage[0]||{},dims=[['levDomain','domain_expertise','Domain expertise'],['levJudgment','judgment_verification','Judgment & verification'],['levSystems','systems_automation','Systems & automation'],['levDistribution','relationships_distribution','Relationships & distribution'],['levAssets','owned_ip_data_assets','Owned IP / data / assets'],['levCapital','capital_allocation','Capital allocation']];const values=dims.map(x=>Number(latest[x[1]])||0),avg=Math.round(values.reduce((a,b)=>a+b,0)/values.length),min=Math.min(...values),bottleneck=dims[values.indexOf(min)]?.[2]||'Not measured';
 host.innerHTML=`<div class="card"><div class="eyebrow">Personal Leverage Balance Sheet</div><h2>Track whether AI is increasing what you can produce, control and own.</h2><p class="muted">This is not a personality score. Record a snapshot only when you can explain the evidence behind it. The goal is to reduce dependence on raw labor while increasing expertise, systems, distribution, ownership and disciplined capital allocation.</p>${leverage.length?`<div class="grid three"><div class="metric"><span>Composite</span><strong>${avg}</strong><small>latest self-audit</small></div><div class="metric"><span>Current bottleneck</span><strong class="metric-text">${esc(bottleneck)}</strong><small>${min}/100</small></div><div class="metric"><span>Snapshots</span><strong>${leverage.length}</strong><small>history retained</small></div></div>`:''}</div><div class="card" style="margin-top:14px"><div class="form-grid">${dims.map(x=>`<div class="field"><label>${x[2]} 0–100</label><input id="${x[0]}" type="number" min="0" max="100" value="${Number(latest[x[1]])||0}"></div>`).join('')}</div><div class="field" style="margin-top:12px"><label>Evidence note</label><textarea id="levEvidence" placeholder="What artifacts, results, responsibilities, systems, audience, IP or capital decisions justify these numbers?"></textarea></div><button id="saveLeverage" class="btn primary">Record snapshot</button></div><div style="margin-top:14px">${leverage.length?leverage.slice(0,6).map(x=>`<div class="card" style="margin-bottom:10px"><div class="eyebrow">${new Date(x.created_at).toLocaleDateString()}</div><div class="grid three"><div><b>${x.domain_expertise}</b><div class="small muted">Domain</div></div><div><b>${x.systems_automation}</b><div class="small muted">Systems</div></div><div><b>${x.owned_ip_data_assets}</b><div class="small muted">Owned assets</div></div></div>${x.evidence_note?`<p class="muted small">${esc(x.evidence_note)}</p>`:''}</div>`).join(''):''}</div>`;$('#saveLeverage').onclick=saveLeverage;
}
async function saveLeverage(){const n=id=>Math.max(0,Math.min(100,+$('#'+id).value||0));const row={user_id:S.user.id,domain_expertise:n('levDomain'),judgment_verification:n('levJudgment'),systems_automation:n('levSystems'),relationships_distribution:n('levDistribution'),owned_ip_data_assets:n('levAssets'),capital_allocation:n('levCapital'),evidence_note:$('#levEvidence').value.trim(),created_at:new Date().toISOString()};if(!row.evidence_note)return toast('Add a short evidence note before recording a leverage snapshot.');const{error}=await sb.from('hlo_leverage_snapshots').insert(row);if(error)return toast(error.message);toast('Leverage snapshot recorded');renderLeverage()}
