import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,x-nexus-worker-token","Access-Control-Allow-Methods":"POST,OPTIONS"};
const base=()=>Deno.env.get('SUPABASE_URL')||'https://dmdgkjksouhhsuojthav.supabase.co';
const service=()=>Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const h=()=>({'content-type':'application/json','apikey':service(),'authorization':`Bearer ${service()}`});
const clean=(v:any,n=2000)=>String(v??'').slice(0,n);
async function config(){const r=await fetch(`${base()}/rest/v1/nexus_worker_config?key=eq.email_worker&select=secret_hash,enabled`,{headers:h()});if(!r.ok)throw new Error('CONFIG_LOAD_FAILED');return (await r.json())?.[0]||null}
async function digest(v:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function patch(id:string,p:any){await fetch(`${base()}/rest/v1/nexus_email_outbox?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{...h(),'Prefer':'return=minimal'},body:JSON.stringify({...p,updated_at:new Date().toISOString()})})}
async function health(status:'healthy'|'degraded'|'failed',summary:string,details:any={}){await fetch(`${base()}/rest/v1/nexus_system_health`,{method:'POST',headers:{...h(),'Prefer':'return=minimal'},body:JSON.stringify({check_name:'email_delivery',status,summary,details})}).catch(()=>{})}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return new Response('method not allowed',{status:405,headers:cors});try{const cfg=await config();const token=req.headers.get('x-nexus-worker-token')||'';if(!cfg?.enabled||!token||await digest(token)!==cfg.secret_hash)return new Response(JSON.stringify({ok:false,error:'Unauthorized'}),{status:401,headers:{...cors,'content-type':'application/json'}});const resend=Deno.env.get('RESEND_API_KEY'),from=Deno.env.get('NEXUS_EMAIL_FROM')||'Nexus Intelligence <contact@nexusintelligence.live>';if(!resend){await health('failed','Transactional email provider is not configured.',{missing:['RESEND_API_KEY'],sender:from});return new Response(JSON.stringify({ok:false,error:'Email provider not configured'}),{status:503,headers:{...cors,'content-type':'application/json'}})}
const claim=await fetch(`${base()}/rest/v1/rpc/nexus_claim_email_batch`,{method:'POST',headers:h(),body:JSON.stringify({p_limit:25})});if(!claim.ok)throw new Error(`CLAIM_${claim.status}`);const rows=await claim.json();let sent=0,retried=0,failed=0;
for(const row of rows){try{const action=row.action_url?`${Deno.env.get('NEXUS_PUBLIC_ORIGIN')||'https://nexus-intelligence-v3-preview.vercel.app'}${row.action_url}`:null;const body=clean(row.body_text,12000)+(action?`\n\nOpen Nexus: ${action}`:'');const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${resend}`,'content-type':'application/json'},body:JSON.stringify({from,to:[row.recipient_email],subject:clean(row.subject,250),text:body,headers:{'X-Entity-Ref-ID':row.id}})});const p=await r.json().catch(()=>({}));if(!r.ok){const permanent=[400,401,403,404,422].includes(r.status);await patch(row.id,{status:permanent||Number(row.attempts)>=4?'failed':'queued',available_at:new Date(Date.now()+(permanent?0:Math.min(60,15*Math.max(1,Number(row.attempts))))*60000).toISOString(),last_attempt_at:new Date().toISOString(),failure_class:permanent?'permanent':'transient',last_error:clean(p?.message||`Provider ${r.status}`,1000),provider_status:String(r.status)});permanent||Number(row.attempts)>=4?failed++:retried++;continue}await patch(row.id,{status:'sent',sent_at:new Date().toISOString(),provider_message_id:p?.id||null,last_attempt_at:new Date().toISOString(),failure_class:null,last_error:null,provider_status:'accepted'});sent++}catch(e){await patch(row.id,{status:Number(row.attempts)>=4?'failed':'queued',available_at:new Date(Date.now()+15*60000).toISOString(),last_attempt_at:new Date().toISOString(),failure_class:'transient',last_error:clean((e as Error).message,1000)});retried++}}
const oldest=await fetch(`${base()}/rest/v1/nexus_email_outbox?status=eq.queued&select=created_at&order=created_at.asc&limit=1`,{headers:h()}).then(r=>r.ok?r.json():[]);const age=oldest?.[0]?Math.round((Date.now()-Date.parse(oldest[0].created_at))/60000):0;await health(failed?'degraded':age>30?'degraded':'healthy',`Email worker claimed ${rows.length}; sent ${sent}; retrying ${retried}; failed ${failed}.`,{claimed:rows.length,sent,retried,failed,oldest_queue_minutes:age,sender:from});return new Response(JSON.stringify({ok:true,claimed:rows.length,sent,retried,failed,oldest_queue_minutes:age}),{headers:{...cors,'content-type':'application/json'}})
}catch(e){console.error(e);await health('failed','Email worker execution failed.',{error:clean((e as Error).message,500)});return new Response(JSON.stringify({ok:false,error:'Email worker failed'}),{status:500,headers:{...cors,'content-type':'application/json'}})}});
