import {bookingConfigured,freeBusy,updateCalendarEvent,deleteCalendarEvent} from '../_lib/google-calendar.js';
const H={'content-type':'application/json','cache-control':'no-store'},S='https://dmdgkjksouhhsuojthav.supabase.co';
const svc=env=>({'content-type':'application/json','apikey':env.SUPABASE_SERVICE_ROLE_KEY,'authorization':`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`});
const clean=(v,n)=>String(v??'').trim().slice(0,n);
async function rowFor(env,mode,token){const col=mode==='cancel'?'cancellation_token':'reschedule_token';const r=await fetch(`${S}/rest/v1/nexus_discovery_requests?${col}=eq.${encodeURIComponent(token)}&select=id,email,booking_status,calendar_event_id,meeting_url,confirmed_start,confirmed_end,timezone,cancelled_at`,{headers:svc(env)});if(!r.ok)throw new Error('BOOKING_LOOKUP_FAILED');return (await r.json())?.[0]||null}
export async function onRequestGet(context){try{const u=new URL(context.request.url),mode=u.searchParams.get('mode'),token=clean(u.searchParams.get('token'),80);if(!['cancel','reschedule'].includes(mode)||!token)return new Response(JSON.stringify({ok:false,error:'Invalid booking link.'}),{status:400,headers:H});const row=await rowFor(context.env,mode,token);if(!row)return new Response(JSON.stringify({ok:false,error:'Booking link not found or expired.'}),{status:404,headers:H});return new Response(JSON.stringify({ok:true,booking:{status:row.booking_status,start:row.confirmed_start,end:row.confirmed_end,timezone:row.timezone,meeting_url:row.meeting_url,cancelled_at:row.cancelled_at}}),{headers:H})}catch(e){return new Response(JSON.stringify({ok:false,error:'Booking details could not be loaded.'}),{status:500,headers:H})}}
export async function onRequestPost(context){const env=context.env;if(!bookingConfigured(env))return new Response(JSON.stringify({ok:false,error:'Calendar booking is not configured.'}),{status:503,headers:H});try{const body=await context.request.json(),mode=clean(body.mode,20),token=clean(body.token,80);if(!['cancel','reschedule'].includes(mode)||!token)return new Response(JSON.stringify({ok:false,error:'Invalid booking action.'}),{status:400,headers:H});const row=await rowFor(env,mode,token);if(!row)return new Response(JSON.stringify({ok:false,error:'Booking link not found or expired.'}),{status:404,headers:H});if(mode==='cancel'){
  if(row.cancelled_at||row.booking_status==='cancelled')return new Response(JSON.stringify({ok:true,status:'cancelled'}),{headers:H});if(row.calendar_event_id)await deleteCalendarEvent(env,row.calendar_event_id);await fetch(`${S}/rest/v1/nexus_discovery_requests?id=eq.${encodeURIComponent(row.id)}`,{method:'PATCH',headers:{...svc(env),'Prefer':'return=minimal'},body:JSON.stringify({booking_status:'cancelled',cancelled_at:new Date().toISOString()})});return new Response(JSON.stringify({ok:true,status:'cancelled'}),{headers:H});
  }
  const start=new Date(body.start),end=new Date(body.end),timezone=clean(body.timezone,80)||row.timezone||'America/New_York';if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||end<=start)return new Response(JSON.stringify({ok:false,error:'Choose a valid new time.'}),{status:400,headers:H});const busy=await freeBusy(env,start.toISOString(),end.toISOString());const oldStart=Date.parse(row.confirmed_start||0),oldEnd=Date.parse(row.confirmed_end||0);if(busy.some(x=>{const a=Date.parse(x.start),b=Date.parse(x.end);const sameOld=Math.abs(a-oldStart)<1000&&Math.abs(b-oldEnd)<1000;return !sameOld&&start.getTime()<b&&end.getTime()>a}))return new Response(JSON.stringify({ok:false,error:'That time is no longer available.'}),{status:409,headers:H});if(!row.calendar_event_id)throw new Error('CALENDAR_EVENT_MISSING');const event=await updateCalendarEvent(env,row.calendar_event_id,{start:start.toISOString(),end:end.toISOString(),timezone});await fetch(`${S}/rest/v1/nexus_discovery_requests?id=eq.${encodeURIComponent(row.id)}`,{method:'PATCH',headers:{...svc(env),'Prefer':'return=minimal'},body:JSON.stringify({booking_status:'confirmed',requested_start:start.toISOString(),confirmed_start:event.start?.dateTime||start.toISOString(),confirmed_end:event.end?.dateTime||end.toISOString(),timezone,cancelled_at:null})});return new Response(JSON.stringify({ok:true,status:'confirmed',start:event.start?.dateTime||start.toISOString(),end:event.end?.dateTime||end.toISOString()}),{headers:H});
}catch(error){console.error('booking manage',error);return new Response(JSON.stringify({ok:false,error:'The booking change could not be completed.'}),{status:502,headers:H})}}
