import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {database,asUser} from './fixture.mjs';
export const commerceMigrations=(await fs.readdir(new URL('../../supabase/migrations/',import.meta.url))).filter(n=>/^202609(?:0[789]|10)/.test(n)&&!n.includes('000100_')&&!n.includes('000200_')&&!n.includes('launch_security_controls')&&!n.includes('retire_unsafe_snapshot')).sort();
const admin='00000000-0000-4000-8000-000000000001',client='00000000-0000-4000-8000-000000000002',company='00000000-0000-4000-8000-000000000003',foreign='00000000-0000-4000-8000-000000000004';
test('Discovery report retains real input, limits free scope and activates exactly one included Build only after its verified deposit',async()=>{
 const db=await database(commerceMigrations);
 try{
 await db.exec(`insert into nexus_commercial_offerings(code,name,description,client_outcome,pricing_model,sort_order) values ('find','Legacy included diagnosis','Retained entitlement','Reviewed diagnosis','Included',99); insert into auth.users values ('${admin}'),('${client}'); insert into nexus_platform_admins(user_id) values ('${admin}'); insert into nexus_companies(id,name,created_by) values ('${company}','Synthetic Construction QA','${admin}'),('${foreign}','Other','${admin}'); update nexus_delivery_settings set checkout_enabled=true,stripe_account_id='acct_test';`);
 const template=(await db.query("select title,default_recipe from nexus_resolution_catalog where code='build_estimate_follow_up'")).rows[0];
 await asUser(db,admin,()=>db.query('select relystra_save_library_build($1,$2,$3,true)',['build_estimate_follow_up',template.title,template.default_recipe]));
 assert.equal((await db.query("select jsonb_array_length(default_recipe->'change_log') n from nexus_resolution_catalog where code='build_estimate_follow_up'")).rows[0].n,1);
 await asUser(db,client,()=>assert.rejects(db.query('select relystra_save_offer($1,100,200,50)',['cleanup_sprint']),/Administrator/));
 await asUser(db,admin,async()=>{
  await assert.rejects(db.query('select relystra_save_offer($1,1,2,50)',['free_discovery']),/Valid Offer/);
  await db.query('select relystra_save_offer($1,75000,150000,50)',['cleanup_sprint']);
  const ladder=(await db.query('select relystra_offer_ladder() data')).rows[0].data;assert.equal(ladder.length,6);assert.equal(ladder.find(o=>o.code==='cleanup_sprint').min_price_cents,75000);
  await assert.rejects(db.query('select relystra_save_local_addons($1)',[[{name:'Bad price',minutes:[60,90],price_cents:0}]]),/positive price/);
 });
 const primary={template_code:'build_bid_intake',offer_code:'cleanup_sprint',name:'Bid Intake Tracker',problem:'Bids lose owners',outcome:'Each bid has a clear owner',price_cents:100000,deposit_cents:50000,currency:'usd',duration_min:2,duration_max:4,scope_in:['One intake workflow'],scope_out:['Estimating services'],inputs:['Authorized bid records'],deliverables:['Populated tracker','Usage and maintenance guide'],acceptance_criteria:['A sample bid reaches its owner']};
 const report={heard:'Bid intake is scattered across inboxes.',bottleneck:'No single owner for new bid requests.',primary,later:[]};
 const contact={full_name:'Synthetic QA Owner',email:'construction-qa@example.invalid'};
 const save=report=>asUser(db,admin,()=>db.query('select relystra_save_basic_report(null,$1,$2,$3,$4,true) id',[company,contact,'Synthetic authorized QA transcript: bid requests arrive in multiple inboxes and ownership is unclear.',report]).then(r=>r.rows[0].id));
 await assert.rejects(save({...report,later:[{},{},{}]}),/at most two/);
 await assert.rejects(save({...report,primary:{...primary,deposit_cents:100001}}),/valid price/);
 const discovery=await asUser(db,admin,()=>db.query('select relystra_discovery_workspace($1,null) s',[company]).then(r=>r.rows[0].s));
 const original=crypto.randomUUID();await db.query("insert into nexus_documents(id,company_id,storage_path,file_name,category,uploaded_by) values($1,$2,$3,'Original.txt','Discovery Transcript',$4)",[original,company,company+'/original.txt',admin]);
 await asUser(db,admin,()=>db.query('select relystra_discovery_workspace($1,null)',[company]));
 const id=await save({...report,discovery_engagement_id:discovery.id});
 const token=await asUser(db,admin,()=>db.query('select relystra_share_basic_report($1) token',[id]).then(r=>r.rows[0].token));
 await asUser(db,client,async()=>{assert.equal((await db.query('select * from nexus_discovery_requests')).rows.length,0);await assert.rejects(db.query('select relystra_basic_report_access($1)',[token]),/permission denied/)});
 const access=async(op='view')=>(await db.query('select relystra_basic_report_access($1,$2) report',[token,op])).rows[0].report;
 const visible=await access();assert.equal(visible.primary.price_cents,100000);assert.ok(!JSON.stringify(visible).includes('transcript'));assert.ok(!JSON.stringify(visible).includes('price_override_reason'));
 assert.equal((await db.query('select * from nexus_company_members')).rows.length,0,'no pre-purchase membership');
 const accepted=await access('accept');assert.equal(accepted.plan_status,'awaiting_payment');
 assert.equal((await access('accept')).plan_id,accepted.plan_id,'accept replay returns same plan');
 assert.equal((await db.query('select * from nexus_projects')).rows.length,0,'acceptance does not activate work');
 const planId=accepted.plan_id;
 await asUser(db,client,()=>assert.rejects(db.query('select * from nexus_qa_fixture_runs'),/permission denied/));
 await db.query('insert into nexus_qa_fixture_runs(run_key,company_id,admin_user_id,client_user_id) values ($1,$2,$3,$4)',['local-verified-bootstrap',company,admin,client]);
 await db.exec('update nexus_delivery_settings set payment_livemode=true');
 await db.query('select relystra_claim_checkout($1,$2)',[planId,admin]);
 assert.equal((await db.query('select checkout_livemode from nexus_build_plans where id=$1',[planId])).rows[0].checkout_livemode,false,'registered ephemeral QA stays in Stripe test mode after live launch');
 await db.exec('update nexus_delivery_settings set payment_livemode=false');
 await db.query("update nexus_build_plans set checkout_session_id='cs_initial' where id=$1",[planId]);
 const plan=(await db.query('select * from nexus_build_plans where id=$1',[planId])).rows[0];assert.equal(plan.items.length,1);
 const pay=async(id,amount,event='evt_initial',session='cs_initial',intent='pi_initial')=>db.query('select relystra_record_verified_payment($1,$2,$3,$4,$5,$6,$7,$8,$9) id',[id,event,session,intent,amount,'usd',false,(await db.query('select snapshot_digest from nexus_build_plans where id=$1',[id])).rows[0].snapshot_digest,'acct_test']);
 await assert.rejects(pay(planId,49999),/amount/);
 const project=(await pay(planId,50000)).rows[0].id;
 assert.equal((await pay(planId,50000)).rows[0].id,project,'webhook replay does not duplicate project');
 const retained=await asUser(db,admin,()=>db.query('select relystra_workspace_snapshot($1,$2) s',[company,project]).then(r=>r.rows[0].s));
 assert.equal(retained.free_discovery.id,discovery.id,'payment retains original discovery engagement automatically');
 assert.equal(retained.free_discovery.documents[0].id,original);
 assert.equal((await db.query('select id from relystra_evidence_scope($1,$2)',[company,project])).rows[0].id,original,'full diagnosis and coverage retain the same authorized source');
 await assert.rejects(db.query("insert into nexus_diagnosis_runs(company_id,status,created_by) values($1,'queued',$2)",[company,admin]),/Full Diagnosis requires payment/);
 await assert.rejects(db.query("insert into nexus_diagnosis_runs(company_id,status,created_by) values($1,'queued',$2)",[foreign,admin]),/Full Diagnosis requires payment/);
 assert.equal((await db.query('select private.relystra_full_diagnosis_access($1,$2,null) access',[company,crypto.randomUUID()])).rows[0].access,false,'paid plan cannot authorize another project');
 assert.equal((await db.query('select * from nexus_system_cards')).rows.length,1);
 const firstBuild=(await db.query('select id from nexus_system_cards where project_id=$1',[project])).rows[0].id;
 await asUser(db,admin,()=>assert.rejects(db.query('select relystra_save_brief($1,$2,true)',[firstBuild,{}]),/Full Diagnosis/));
 assert.equal((await db.query('select * from nexus_company_entitlements where company_id=$1',[company])).rows.length,1,'Full Diagnosis included');
 assert.match((await db.query('select content from nexus_discovery_context_entries where project_id=$1',[project])).rows[0].content,/Synthetic authorized QA transcript/);
 assert.equal((await db.query('select context_diagnosis_run_id from nexus_projects where id=$1',[project])).rows[0].context_diagnosis_run_id,null,'no invented diagnosis');
 await asUser(db,admin,async()=>{
 const summary=(await db.query('select relystra_payment_summary($1) summary',[company])).rows[0].summary[0];assert.equal(summary.paid_cents,50000);assert.equal(summary.balance_cents,50000);
 await assert.rejects(db.query('select relystra_publish_final($1)',[project]),/balance/);
 });
 const run=(await db.query("insert into nexus_diagnosis_runs(company_id,project_id,status,analysis_result,created_by) values ($1,$2,'approved',$3,$4) returning id",[company,project,{opportunity_backlog:[{title:'Test finding from QA evidence'}]},admin])).rows[0].id;
 assert.equal((await db.query('select context_diagnosis_run_id from nexus_projects where id=$1',[project])).rows[0].context_diagnosis_run_id,run);
 await asUser(db,client,()=>assert.rejects(db.query('select relystra_request_build_input($1,$2,$3)',[firstBuild,'Samples','Two authorized sample records']),/Administrator/));
 const inputRequest=await asUser(db,admin,()=>db.query('select relystra_request_build_input($1,$2,$3) id',[firstBuild,'Samples','Two authorized sample records']).then(r=>r.rows[0].id));
 const briefPatch={tools_platforms:['Test register'],users_roles:['QA Owner'],automation_requirements:['None'],integrations:['None'],assumptions:['Authorized test data'],risks:['Backup required'],test_inputs:['Two test rows']};
 await asUser(db,admin,()=>assert.rejects(db.query('select relystra_save_brief($1,$2,true)',[firstBuild,briefPatch]),/required Build inputs/));
 await assert.rejects(db.query('update nexus_document_requests set company_id=$1 where id=$2',[foreign,inputRequest]),/immutable/);
 await asUser(db,admin,()=>assert.rejects(db.query('select relystra_review_build_input($1,true,$2)',[inputRequest,'Reviewed synthetic records']),/uploaded private file/));
 const inputDoc=(await db.query("insert into nexus_documents(company_id,project_id,request_id,file_name,storage_path,mime_type,size_bytes,uploaded_by,status) values ($1,$2,$3,'synthetic.csv',$4,'text/csv',40,$5,'shared') returning id",[company,project,inputRequest,company+'/synthetic.csv',client])).rows[0].id;
 await db.query("insert into storage.objects(bucket_id,name) values ('nexus-client-documents',$1)",[company+'/synthetic.csv']);
 // Production upload triggers set the received pointer; external document lifecycle is stubbed in this fixture.
 await db.query("update nexus_document_requests set fulfilled_document_id=$1,status='received',evidence_status='uploaded' where id=$2",[inputDoc,inputRequest]);
 await asUser(db,client,()=>assert.rejects(db.query('select relystra_review_build_input($1,true,$2)',[inputRequest,'Client cannot approve this upload']),/Administrator/));
 await asUser(db,admin,()=>db.query('select relystra_review_build_input($1,false,$2)',[inputRequest,'Please include the missing owner column']));
 await asUser(db,admin,()=>assert.rejects(db.query('select relystra_save_brief($1,$2,true)',[firstBuild,briefPatch]),/required Build inputs/));
 await asUser(db,admin,()=>db.query('select relystra_review_build_input($1,true,$2)',[inputRequest,'Reviewed synthetic owner column and permitted records']));
 await asUser(db,admin,()=>db.query('select relystra_save_brief($1,$2,true)',[firstBuild,briefPatch]));
 assert.equal((await db.query('select count(*)::integer n from nexus_tasks where build_id=$1',[firstBuild])).rows[0].n,13);

 await assert.rejects(db.query('update nexus_projects set context_diagnosis_run_id=null where id=$1',[project]),/immutable/);
 const balance=await asUser(db,admin,()=>db.query('select relystra_create_balance_plan($1) id',[planId]).then(r=>r.rows[0].id));
 await db.query('select relystra_claim_checkout($1,$2)',[balance,admin]);await db.query("update nexus_build_plans set checkout_session_id='cs_balance' where id=$1",[balance]);
 assert.equal((await pay(balance,50000,'evt_balance','cs_balance','pi_balance')).rows[0].id,project);
 assert.equal((await db.query('select * from nexus_projects')).rows.length,1,'balance creates no new work');
 await asUser(db,admin,()=>assert.rejects(db.query('select relystra_create_diagnosis_plan($1)',[company]),/included/));
 await assert.rejects(db.query('update nexus_build_plans set deposit_cents=1 where id=$1',[planId]),/immutable/);
 const qualification=Object.fromEntries(['impact','urgency','effort','dependency_readiness','client_readiness','confidence'].map(k=>[k,{level:k==='effort'?'low':'high',reason:'Supported by the synthetic approved finding.'}]));
 const spec={name:'Estimate follow-up',outcome:'Each estimate receives an owned follow-up',problem:'Follow-ups missed',diagnosis_run_id:run,template_code:'build_estimate_follow_up',source_path:'opportunity_backlog/0',completed_action_ids:[],qualification,operational_benefit:'Fewer missed follow-ups',commercial_state:'needs_discussion',placement:'next',offer_code:'cleanup_sprint',complexity_scores:[1,1,1,1,1],complexity:'simple',price_cents:100000,deposit_cents:50000,currency:'usd',duration_min:3,duration_max:5,scope_in:['One follow-up process'],scope_out:['No sales outreach'],required_inputs:['Client-approved estimate records'],acceptance_criteria:['Representative estimate can be followed through'],dependencies:[]};
 await db.query("insert into nexus_company_members(company_id,user_id,member_role,active) values ($1,$2,'owner',true)",[company,client]);
 await db.query('select relystra_complete_initial_invite($1,$2)',[planId,client]);
 await db.query('select relystra_complete_initial_invite($1,$2)',[planId,client]);
 assert.equal((await db.query('select member_role from nexus_company_members where company_id=$1 and user_id=$2',[company,client])).rows[0].member_role,'owner');
 assert.equal((await db.query('select invited_user_id from nexus_discovery_requests where id=$1',[id])).rows[0].invited_user_id,client);
 const extra=await asUser(db,admin,()=>db.query("select relystra_save_build($1,null,$2,'approve') id",[company,spec]).then(r=>r.rows[0].id));
 await asUser(db,client,async()=>{
  const roadmap=(await db.query('select relystra_roadmap($1) data',[company])).rows[0].data;
  assert.equal(roadmap.included.length,1);assert.equal(roadmap.recommendations.length,1);assert.equal(roadmap.recommendations[0].commercial_state,'needs_discussion');
  assert.ok(!JSON.stringify(roadmap).includes('Supported by the synthetic'),'internal scoring rationale is not client-visible');
  await assert.rejects(db.query('select relystra_roadmap($1)',[foreign]),/Company access/);
  await assert.rejects(db.query('select relystra_create_build_plan($1,$2)',[company,[extra]]),/Confirm scope/);
  await db.query("select relystra_build_interest($1,$2,'discuss')",[company,extra]);
 });
 await asUser(db,admin,()=>db.query("select relystra_save_build($1,$2,$3,'approve')",[company,extra,{commercial_state:'commercially_ready'}]));
 const other=await asUser(db,admin,()=>db.query("select relystra_save_build($1,null,$2,'approve') id",[company,{...spec,name:'AR Follow-Up',template_code:'build_ar_follow_up',commercial_state:'commercially_ready',placement:'later',dependencies:[extra]}]).then(r=>r.rows[0].id));
 await asUser(db,client,async()=>{
  await assert.rejects(db.query('select relystra_create_build_plan($1,$2)',[company,[other]]),/required dependency/);
  const extraPlanId=(await db.query('select relystra_create_build_plan($1,$2) id',[company,[extra,other]])).rows[0].id;
  const extraPlan=(await db.query('select * from nexus_build_plans where id=$1',[extraPlanId])).rows[0];
  assert.equal(extraPlan.total_cents,200000);assert.equal(extraPlan.deposit_cents,100000);assert.equal(extraPlan.items.length,2);
  assert.ok(extraPlan.items.every(i=>i.template_code!=='build_bid_intake'),'original Build is not charged again');
  assert.equal(extraPlan.duration_min,9);assert.equal(extraPlan.duration_max,13);
  assert.equal(extraPlan.duration_assumptions.items[1].start_min,3);
 });
 const parallel=(await db.query("select private.relystra_schedule($1,2,1,2) data",[[{id:'a',duration_min:5,duration_max:5},{id:'b',duration_min:5,duration_max:5},{id:'c',duration_min:5,duration_max:5}]])).rows[0].data;
  assert.equal(parallel.min_days,13,'three five-day Builds on two slots need ten days plus QA and review');
 await assert.rejects(db.query('select private.relystra_schedule($1,1,1,2)',[[{id:'a',duration_min:1,duration_max:1,dependencies:['b']},{id:'b',duration_min:1,duration_max:1,dependencies:['a']}]]),/cycle/);
 await asUser(db,admin,()=>assert.rejects(db.query('select relystra_cleanup_qa_commerce($1)',['local-verified-bootstrap']),/permission denied/));
 await assert.rejects(db.query('select relystra_cleanup_qa_commerce($1)',['local-verified-bootstrap']),/Registered QA/);
 await db.query("update nexus_companies set name='Nexus QA local-verified-bootstrap' where id=$1",[company]);
 await db.query("update nexus_delivery_payment_events set livemode=true where plan_id=$1",[planId]);
 await assert.rejects(db.query('select relystra_cleanup_qa_commerce($1)',['local-verified-bootstrap']),/Live commercial records/);
 assert.equal((await db.query('select count(*)::integer n from nexus_projects where company_id=$1',[company])).rows[0].n,1,'refused cleanup retains paid work');
 await db.query("update nexus_delivery_payment_events set livemode=false where plan_id=$1",[planId]);
 await db.query('select relystra_cleanup_qa_commerce($1)',['local-verified-bootstrap']);
 for(const table of ['nexus_discovery_requests','nexus_build_plans','nexus_projects','nexus_opportunities'])assert.equal((await db.query(`select count(*)::integer n from ${table} where company_id=$1`,[company])).rows[0].n,0,'tenant deletion removes '+table+' including cyclic Discovery/plan links');
 assert.equal((await db.query('select count(*)::integer n from nexus_companies where id=$1',[foreign])).rows[0].n,1,'unrelated tenant remains');
 }finally{await db.close()}
});
