import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs/promises';

const read=name=>fs.readFile(new URL(name,import.meta.url),'utf8');
const quote=name=>'"'+name.replaceAll('"','""')+'"';

export async function database(extraMigrations=[]){
  const db=new PGlite();
  await db.exec(`create schema auth; create schema private; create schema storage;
    create role authenticated; create role anon; create role service_role bypassrls;
    create table auth.users(id uuid primary key);
    create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
    create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
    grant usage on schema public,auth,private to authenticated;
    grant execute on function auth.uid() to authenticated;`);
  const extra=JSON.parse(await read('baseline-extra-metadata.json'));
  const columns=[...JSON.parse(await read('baseline-columns.json')),...extra.columns];
  const identities=JSON.parse(await read('baseline-identities.json'));
  const controls=JSON.parse(await read('baseline-controls.json'));
  controls.constraints.push(...extra.constraints);
  const names=[...new Set(columns.map(row=>row.table_name))];
  for(const name of names){
    const fields=columns.filter(row=>row.table_name===name).map(row=>`${quote(row.column_name)} ${row.column_type}${identities.some(i=>i.table_name===name&&i.column_name===row.column_name)?' generated by default as identity':row.default_value?' default '+row.default_value:''}${row.not_null?' not null':''}`);
    await db.exec(`create table public.${quote(name)} (${fields.join(',')});`);
  }
  for(const constraint of controls.constraints.filter(row=>!/FOREIGN KEY/.test(row.definition)))
    await db.exec(`alter table public.${quote(constraint.table)} add constraint ${quote(constraint.name)} ${constraint.definition};`);
  for(const constraint of controls.constraints.filter(row=>/FOREIGN KEY/.test(row.definition))){
    const target=constraint.definition.match(/REFERENCES (\w+(?:\.\w+)?)/)?.[1];
    if(target==='auth.users'||names.includes(target))await db.exec(`alter table public.${quote(constraint.table)} add constraint ${quote(constraint.name)} ${constraint.definition};`);
  }
  await db.exec(`create function public.nexus_is_platform_admin() returns boolean language sql stable security definer set search_path='' as $$
    select exists(select 1 from public.nexus_platform_admins where user_id=auth.uid()) $$;`);
  await db.exec(await read('baseline-rpcs.sql'));
  for(const name of names)await db.exec(`alter table public.${quote(name)} enable row level security;`);
  for(const policy of controls.policies){
    await db.exec(`create policy ${quote(policy.policyname)} on public.${quote(policy.tablename)} as ${policy.permissive} for ${policy.cmd} to ${policy.roles.map(quote).join(',')}${policy.qual?' using ('+policy.qual+')':''}${policy.with_check?' with check ('+policy.with_check+')':''};`);
  }
  await db.exec(`grant select,insert,update,delete on all tables in schema public to authenticated;`);
  for(const trigger of controls.triggers.filter(row=>/private.nexus_(enforce_task_update_boundary|guard_client_task_update|enforce_task_dependency_order|sync_task_owner)\(/.test(row.definition)))
    await db.exec(trigger.definition+';');
  // External notification/release engines are intentionally outside this local database fixture.
  // Their schema is exercised at deployment integration QA; no outbound services run here.
  for(const name of ['nexus_notify_client_on_task','nexus_notify_newly_unblocked_client_tasks','nexus_create_internal_release_chain','nexus_apply_diagnosis_action_templates_trigger','nexus_notify_admins_on_task','nexus_notify_admins_on_client_task_update'])
    await db.exec(`create function private.${name}() returns trigger language plpgsql as $$ begin return new; end $$;`);
  const migrations=['20260907000100_relystra_prebuild_actions.sql','20260907000200_relystra_delivery_catalog.sql',...extraMigrations];
  for(const migration of migrations)await db.exec(await read('../../supabase/migrations/'+migration));
  return db;
}

export async function asUser(db,id,fn){
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);
  await db.exec('set role authenticated');
  try{return await fn()}finally{await db.exec('reset role')}
}
