import {test,expect} from '../playwright/node_modules/@playwright/test/index.mjs';
const file=(name,text)=>({name,mimeType:'text/plain',buffer:Buffer.from(text)});
test('Full Diagnosis loads its own scoped access when the journey snapshot is unavailable',async({page},info)=>{
 await page.goto('/qa/delivery-browser/?section=transcript&discovery='+info.project.name);
 await expect(page.getByRole('heading',{name:'Upload Discovery Material',exact:true})).toBeVisible();
 await page.evaluate(async()=>{
  const portal=window.NexusPortal,journey=window.NexusAdminJourney;
  portal.$=id=>document.getElementById(id);portal.sb.auth={onAuthStateChange(){}};
  window.NexusAdminJourney={navigate:journey.navigate,refresh:journey.refresh,snapshot:null};
  await import('/portal-admin-intake.js');await journey.navigate('diagnosis');
 });
 await expect(page.getByRole('button',{name:'Review scope & payment',exact:true})).toBeVisible();
 await expect(page.locator('#queueDiagnosisBtn')).toHaveCount(0);
 await page.getByRole('button',{name:'Open Free Diagnosis',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Free Business Diagnosis',exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Return to Step 1',exact:true})).toBeVisible();
 await page.evaluate(async()=>{window.NexusPortal.state.companyId='different-company';await window.NexusAdminIntake.refresh();});
 await expect(page.locator('#queueDiagnosisBtn')).toHaveCount(0);
 await expect(page.locator('#reloadDiagnosisAccessBtn')).toHaveCount(1);
});
test('multi-document discovery, failed parsing, review, stale revision and persisted history work at this device size',async({page},info)=>{
 test.setTimeout(120000);
 await page.goto('/qa/delivery-browser/?section=transcript&discovery='+info.project.name);
 await expect(page.getByRole('heading',{name:'Upload Discovery Material',exact:true})).toBeVisible();
 const upload=async files=>{const input=await page.locator('[data-discovery-upload] input').elementHandle();await page.evaluate(()=>window.NexusAdminJourney.refresh());expect(await input.evaluate(el=>el.isConnected)).toBe(true);await page.locator('[data-discovery-upload] input').setInputFiles(files);await page.evaluate(()=>window.NexusAdminJourney.refresh());await expect.poll(()=>page.locator('[data-discovery-upload] input').evaluate(el=>el.files.length)).toBe(files.length);await page.getByRole('button',{name:'Upload & process documents',exact:true}).click();};
 await upload([file(`first-${info.project.name}.txt`,'Owner: Estimates arrive by email. Assign the estimator.'),file(`second-${info.project.name}.txt`,'Estimator: Phone requests sometimes bypass the intake sheet.'),file(`third-${info.project.name}.txt`,'Coordinator: Weekly review should reconcile missing request owners.')]);
 await expect(page.locator('[data-discovery-status]')).toHaveText(/Ready to generate|Outdated/,{timeout:60000});
 await page.getByRole('button',{name:'Continue to Step 2 · Free Diagnosis →',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Free Business Diagnosis',exact:true})).toBeVisible();
 let modelStarts=0;page.on('request',request=>{if(request.url().endsWith('/qa-discovery-step')&&request.postDataJSON()?.operation==='discovery_kick')modelStarts++;});
 await page.locator('[data-free-generate]').dblclick();await expect(page.locator('[data-discovery-status]')).toHaveText('Free Diagnosis complete',{timeout:60000});expect(modelStarts).toBe(1);
 for(const name of ['Executive Summary','Diagnosis Snapshot','Highest-Priority Findings','Where Friction Is Occurring','Highest-Value Opportunities','Potential Quick Wins','What Needs Deeper Investigation','Sources Reviewed'])await expect(page.getByRole('heading',{name,exact:true})).toBeVisible();
 const first=await page.locator('[data-free-report]').getAttribute('data-free-report');
 await page.reload();await expect(page.locator('[data-free-report]')).toHaveAttribute('data-free-report',first);
 await page.getByRole('navigation',{name:'Numbered client journey'}).getByRole('button',{name:/Upload Discovery Material/}).click();
 await expect(page.getByRole('heading',{name:'Upload Discovery Material',exact:true})).toBeVisible();
 await upload([file(`broken-${info.project.name}.pdf`,'This is not a valid PDF')]);
 await expect(page.getByRole('alert').filter({hasText:'DOCUMENT_PARSE_ERROR'}).first()).toBeVisible();
 const failed=page.locator('[data-discovery-document]').filter({hasText:`broken-${info.project.name}.pdf`});await failed.getByRole('button',{name:'Reprocess document'}).click();await expect(failed.getByRole('alert')).toContainText('DOCUMENT_PARSE_ERROR');
 await failed.getByRole('button',{name:'Remove from evidence'}).click();
 await expect(page.locator('[data-discovery-status]')).toHaveText(/Outdated/);
 await upload([file(`followup-${info.project.name}.txt`,'Owner: The coordinator checks unassigned requests each Monday.')]);
 await page.getByRole('button',{name:'Continue to Step 2 · Free Diagnosis →',exact:true}).click();
 await expect(page.locator('[data-free-generate]')).toBeEnabled();
 await page.evaluate(()=>{const original=window.NexusPortal.sb.rpc;window.NexusPortal.sb.rpc=async function(name,args){if(name==='relystra_request_free_diagnosis')await new Promise(resolve=>window.releaseGeneration=resolve);return original.call(this,name,args)}});
 await page.locator('[data-free-generate]').click();
 await expect(page.locator('[data-discovery-status]')).toHaveText('Requesting Free Diagnosis…');
 await expect(page.locator('[data-free-generate]')).toHaveCount(0);
 await page.evaluate(()=>window.releaseGeneration());
 await expect(page.locator('[data-discovery-status]')).toHaveText('Free Diagnosis complete',{timeout:60000});
 expect(await page.locator('[data-free-report]').getAttribute('data-free-report')).not.toBe(first);
 await page.locator('[data-free-version]').selectOption(first);await expect(page.locator('[data-free-report]')).toHaveAttribute('data-free-report',first);
 await page.locator('[data-free-version]').selectOption('');await page.getByRole('button',{name:'Continue to Review Findings',exact:true}).click();await expect(page.getByRole('heading',{name:'Review Findings',exact:true})).toBeVisible();
 const size=await page.evaluate(()=>({w:document.documentElement.clientWidth,s:document.documentElement.scrollWidth}));expect(size.s).toBeLessThanOrEqual(size.w+1);
 await page.getByRole('button',{name:'Confirm findings & continue',exact:true}).click();
 await expect(page.getByText('Diagnosis uses the retained production component; this fixture verifies the new delivery components.',{exact:true})).toBeVisible();
 await page.screenshot({path:`test-results/discovery-${info.project.name}.png`,fullPage:true});
});
