import {test,expect} from '@playwright/test';
const ae=process.env.NEXUS_QA_ADMIN_EMAIL,ap=process.env.NEXUS_QA_ADMIN_PASSWORD,ce=process.env.NEXUS_QA_CLIENT_EMAIL,cp=process.env.NEXUS_QA_CLIENT_PASSWORD,companyName=process.env.NEXUS_QA_COMPANY_NAME;
const enabled=process.env.NEXUS_QA_COMMERCIAL_RELEASE==='1';
async function login(page,email,password){await page.goto('/portal');await page.locator('#signInEmail').fill(email);await page.locator('#signInPassword').fill(password);await page.locator('#signInBtn').click();await expect(page.locator('#portalApp')).toBeVisible({timeout:45000});await expect.poll(()=>page.evaluate(()=>!!window.NexusPortal?.state?.user&&!window.__nexusPortalBooting),{timeout:45000}).toBe(true)}
async function rpc(page,name,args){return page.evaluate(async({name,args})=>{const r=await window.NexusPortal.sb.rpc(name,args);if(r.error)throw Error(name+': '+r.error.message);return r.data},{name,args})}
async function rows(page,table,columns,filters){return page.evaluate(async({table,columns,filters})=>{let q=window.NexusPortal.sb.from(table).select(columns);for(const [key,value] of Object.entries(filters))q=q.eq(key,value);const r=await q;if(r.error)throw Error(table+': '+r.error.message);return r.data},{table,columns,filters})}
async function checkout(page,planId,operation='checkout'){return page.evaluate(async({planId,operation})=>{const r=await window.NexusPortal.sb.functions.invoke('nexus-diagnosis-execute?handler=checkout',{body:{plan_id:planId,operation}});if(r.error||r.data?.error)throw Error(r.data?.message||r.data?.error||r.error.message);return r.data},{planId,operation})}
async function payTest(checkoutPage,url){
 // Hard guard: no live Checkout session is ever submitted by this test.
 expect(url).toMatch(/^https:\/\/checkout\.stripe\.com\/.*cs_test_/);
 await checkoutPage.goto(url);await expect(checkoutPage.locator('body')).toContainText(/Relystra/i);
 // Stripe's zero-sized accordion button expands its hit area with CSS and
 // covers the radio. Click the rendered label position as a person would.
 const cardLabel=checkoutPage.getByText('Card',{exact:true});await expect(cardLabel).toBeVisible();
 const cardBox=await cardLabel.boundingBox();expect(cardBox).toBeTruthy();
 await checkoutPage.mouse.click(cardBox.x+cardBox.width/2,cardBox.y+cardBox.height/2);
 async function field(name,value){
  await expect.poll(async()=>{for(const frame of checkoutPage.frames())if(await frame.locator(`input[name="${name}"],select[name="${name}"]`).count())return true;return false},{timeout:30000,message:'Stripe field '+name}).toBe(true);
  for(const frame of checkoutPage.frames()){const el=frame.locator(`[name="${name}"]`).first();if(await el.count()){if((await el.evaluate(e=>e.tagName))==='SELECT')await el.selectOption(value);else await el.fill(value);return}}
 }
 const email=checkoutPage.locator('input[name=email]');if(await email.count())await email.fill(ce);
 await field('cardNumber','4242424242424242');await field('cardExpiry','12/34');await field('cardCvc','123');
 for(const [name,value] of Object.entries({billingName:'Synthetic QA Owner',billingPostalCode:'19720'})){const el=checkoutPage.locator(`[name="${name}"]`);if(await el.count())await el.fill(value)}
 const country=checkoutPage.locator('[name=billingCountry]');if(await country.count())await country.selectOption('US');
 await checkoutPage.locator('button[type=submit]').last().click();
 await checkoutPage.waitForURL(url=>url.hostname!=='checkout.stripe.com',{timeout:60000});
}
const transcript=`SYNTHETIC AUTHORIZED QA TRANSCRIPT. This fictional construction contractor is used only for release acceptance. No genuine client information is represented.
Owner: We have twelve people and six small construction jobs. I personally coordinate estimates, paperwork and invoices. We use email, a shared spreadsheet and folders. We are authorized to use the example records supplied for this test. Our coordinator can maintain a tracker.
Estimator: New bid requests arrive in different inboxes. Sometimes nobody is assigned. We need one intake register with the site, contact, scope, urgency, owner, status and due date. Sample request QA-001 is a lobby floor estimate at Sample North Site, normal urgency, owned by QA Coordinator, status received. QA-002 is a window estimate at Sample South Site, urgent, awaiting clarification from QA Reviewer. No automated bid submission is authorized.
Owner: We agree the first Build is a populated bid-intake register with a backup, usage instructions and a walkthrough. We can supply the two fictional records immediately. Further work is optional.
Estimator: Sent estimates have no reliable follow-up dates and customers call for updates. We need an owner and next-touch date for each estimate, without sending messages automatically.
Coordinator: Project status is copied from email to a weekly update. We lose decisions and action owners from meetings. A meeting action list and a project status view would help. We can provide fictional project and action rows but cannot connect external systems in this test.
Administrator: Closeout requirements are spread across inboxes. We need a missing-document tracker. Invoices occasionally lack a follow-up owner, so an invoice follow-up list is another separate opportunity. We want to compare these after the deeper review. Payroll, safety decisions, accounting calculations and contractual advice are outside the scope.
Owner: We want practical registers, clear owners and fewer missed handoffs. Do not promise savings or ROI numbers. We have no measured baseline for those. Capacity is limited; deliver sequentially when needed. We will review the sample workflow, approved scope and maintenance instructions before handoff.`;
const qualification=Object.fromEntries(['impact','urgency','effort','dependency_readiness','client_readiness','confidence'].map(k=>[k,{level:k==='effort'?'low':'medium',reason:'Administrator review of the labeled synthetic Discovery and approved Full Diagnosis; no measured ROI claimed.'}]));

test('deployed Discovery, real Stripe test settlement, Full Diagnosis, expansion and final handoff',async({page,browser,request},info)=>{
 test.skip(!enabled,'Explicit protected production commercial acceptance dispatch required.');
 expect(ae&&ap&&ce&&cp&&companyName).toBeTruthy();test.setTimeout(24*60*1000);
 await login(page,ae,ap);
 const readiness=await page.evaluate(async()=>{const r=await window.NexusPortal.sb.functions.invoke('nexus-diagnosis-execute',{body:{operation:'payment_readiness'}});if(r.error)throw r.error;return r.data});
 console.log('PAYMENT_READINESS',JSON.stringify(readiness));expect(readiness.modes.test.ready).toBe(true);

 const company=await page.locator('#companySelect option').evaluateAll((options,name)=>options.find(o=>o.textContent.trim()===name)?.value,companyName);expect(company).toBeTruthy();
 await page.goto('/portal?view_mode=admin&company='+company);await expect.poll(()=>page.evaluate(()=>window.NexusPortal?.state.companyId),{timeout:45000}).toBe(company);
 const primary={template_code:'build_bid_intake',offer_code:'cleanup_sprint',name:'QA Bid Intake Register',problem:'Synthetic bids lack clear owners',outcome:'Each synthetic bid has an owner and current status',scope_in:['One manually maintained bid-intake register populated with two authorized synthetic records'],scope_out:['No external integrations, automatic outreach or bid submission'],inputs:['Two labeled synthetic bid requests'],deliverables:['Populated intake register','Validated backup','Usage, maintenance and walkthrough instructions'],acceptance_criteria:['Two sample records persist on refresh and backup/restore retains their fields'],price_cents:100000,deposit_cents:50000,currency:'usd',duration_min:2,duration_max:4};
 const reportId=await rpc(page,'relystra_save_basic_report',{p_id:null,p_company_id:company,p_contact:{full_name:'Synthetic QA Owner',email:ce},p_transcript:transcript,p_report:{heard:'Bid requests and follow-ups are scattered across inboxes.',bottleneck:'New bids have no consistent owner or status.',primary,later:[{template_code:'build_estimate_follow_up',name:'Estimate follow-up',why:'Consider owned next-touch dates after deeper review.'}]},p_approve:true});
 const token=await rpc(page,'relystra_share_basic_report',{p_id:reportId});
 const prospectContext=await browser.newContext({baseURL:info.project.use.baseURL});const prospect=await prospectContext.newPage();
 const clientContext=await browser.newContext({baseURL:info.project.use.baseURL});const client=await clientContext.newPage();
 const payments=await browser.newContext();const paymentPage=await payments.newPage();
 try{
  await prospect.goto('/basic-report#report='+token);await expect(prospect.getByRole('button',{name:'Accept this scope',exact:true})).toBeVisible();await expect(prospect.locator('.report-price')).toHaveText('$1,000.00');
  expect((await rows(page,'nexus_projects','id',{company_id:company})).length).toBe(0);
  await prospect.getByRole('button',{name:'Accept this scope',exact:true}).click();await expect(prospect.getByRole('button',{name:'Continue to secure payment'})).toBeVisible();
  const access=async operation=>{const r=await request.post('/api/basic-report',{data:{token,operation}});const d=await r.json();expect(r.ok(),JSON.stringify(d)).toBe(true);return d};
  const accepted=(await access('view')).report;expect(accepted.plan_status).toBe('awaiting_payment');expect((await access('accept')).report.plan_id).toBe(accepted.plan_id);
  const payment=await access('checkout');expect(payment.livemode).toBe(false);await payTest(prospect,payment.url);
  await expect.poll(async()=>(await access('view')).report.plan_status,{timeout:90000}).toBe('paid');
  const original=(await rows(page,'nexus_projects','id,context_diagnosis_run_id,build_plan_id',{company_id:company,build_plan_id:accepted.plan_id}))[0];expect(original).toBeTruthy();expect(original.context_diagnosis_run_id).toBeNull();
  await expect.poll(async()=>(await rows(page,'nexus_discovery_requests','invited_user_id',{id:reportId}))[0]?.invited_user_id,{timeout:60000}).toBeTruthy();
  await prospect.reload();await expect(prospect.getByText('Your payment is confirmed.',{exact:false})).toBeVisible();
  await login(client,ce,cp);await expect(client.locator('#nexusClientPrimaryNav')).toBeVisible();
  const firstRoadmap=await rpc(client,'relystra_roadmap',{p_company_id:company});expect(firstRoadmap.included).toHaveLength(1);expect(firstRoadmap.payments[0].paid_cents).toBe(50000);
  await page.goto(`/portal?view_mode=admin&company=${company}&project=${original.id}&section=transcript`);
  await expect(page.getByRole('button',{name:'Run Diagnosis',exact:true})).toBeVisible({timeout:45000});await page.getByRole('button',{name:'Run Diagnosis',exact:true}).click();
  let runs=[];await expect.poll(async()=>{runs=await rows(page,'nexus_diagnosis_runs','id,status,transcript_document_id,analysis_result',{company_id:company,project_id:original.id});return runs[0]?.status},{timeout:180000,intervals:[3000,5000]}).toBe('ready_for_review');
  const run=runs[0];expect(run.transcript_document_id).toBeTruthy();expect(run.analysis_result).toBeTruthy();
  await rpc(page,'nexus_approve_diagnosis',{p_run_id:run.id,p_note:'Synthetic release acceptance: reviewed actual generated findings against the retained labeled QA transcript.'});
  expect((await rows(page,'nexus_projects','context_diagnosis_run_id',{id:original.id}))[0].context_diagnosis_run_id).toBe(run.id);
  await page.goto(`/portal?view_mode=admin&company=${company}&project=${original.id}&section=builds`);await expect(page.locator('[data-generate-builds]')).toBeEnabled({timeout:45000});
  await page.locator('[data-generate-builds]').click();await expect(page.locator('[data-generate-builds]')).toBeEnabled({timeout:600000});
  const proposed=await rows(page,'nexus_opportunities','id,title,build_spec,build_review_state',{company_id:company,source_diagnosis_run_id:run.id});expect(proposed.length).toBeGreaterThan(2);expect(proposed.every(o=>o.build_review_state==='proposed')).toBe(true);
  const unique=[...new Map(proposed.filter(o=>o.build_spec.template_code!=='build_bid_intake').map(o=>[o.build_spec.template_code,o])).values()];expect(unique.length).toBeGreaterThanOrEqual(3);
  const candidates=unique.slice(0,3),catalog=await rows(page,'nexus_resolution_catalog','code,default_recipe',{active:true});
  for(let i=0;i<candidates.length;i++){
   const o=candidates[i],template=catalog.find(t=>t.code===o.build_spec.template_code).default_recipe,price=template.default_price_cents;
   await rpc(page,'relystra_save_build',{p_company_id:company,p_id:o.id,p_spec:{qualification,operational_benefit:'Clear ownership and next steps in the approved synthetic workflow.',commercial_state:i===2?'needs_discussion':'commercially_ready',placement:i===2?'later':'next',offer_code:template.default_offer,price_cents:price,deposit_cents:Math.ceil(price/2),currency:'usd',complexity_scores:[1,1,1,1,1],complexity:'simple',duration_min:2,duration_max:3,deliverables:template.deliverables,dependency_override_reason:'Synthetic acceptance scope uses independently supplied records; no external integration is required.',dependencies:[]},p_decision:'approve'});
  }
  let roadmap=await rpc(client,'relystra_roadmap',{p_company_id:company});expect(roadmap.included).toHaveLength(1);expect(roadmap.recommendations).toHaveLength(3);
  await rpc(client,'relystra_build_interest',{p_company_id:company,p_build_id:candidates[2].id,p_intent:'discuss',p_note:'Synthetic client requests scope clarification.'});
  await expect(rpc(client,'relystra_create_build_plan',{p_company_id:company,p_build_ids:[candidates[2].id]})).rejects.toThrow(/Confirm scope/);
  const canceled=await rpc(client,'relystra_create_build_plan',{p_company_id:company,p_build_ids:[candidates[0].id]});const open=await checkout(client,canceled);expect(open.livemode).toBe(false);expect((await checkout(client,canceled,'cancel')).status).toBe('cancelled');expect((await rows(page,'nexus_projects','id',{company_id:company}))).toHaveLength(1);
  const one=await rpc(client,'relystra_create_build_plan',{p_company_id:company,p_build_ids:[candidates[0].id]});const onePay=await checkout(client,one);expect(onePay.livemode).toBe(false);await payTest(paymentPage,onePay.url);
  await expect.poll(async()=>(await rows(page,'nexus_build_plans','status',{id:one}))[0]?.status,{timeout:90000}).toBe('paid');
  await rpc(page,'relystra_save_build',{p_company_id:company,p_id:candidates[2].id,p_spec:{commercial_state:'commercially_ready',dependencies:[candidates[1].id],dependency_reason:'Synthetic dependent view requires the preceding tracker to be populated.'},p_decision:'approve'});
  await expect(rpc(client,'relystra_create_build_plan',{p_company_id:company,p_build_ids:[candidates[2].id]})).rejects.toThrow(/dependency/);
  const multi=await rpc(client,'relystra_create_build_plan',{p_company_id:company,p_build_ids:[candidates[1].id,candidates[2].id]});const multiPay=await checkout(client,multi);expect(multiPay.livemode).toBe(false);await payTest(paymentPage,multiPay.url);
  await expect.poll(async()=>(await rows(page,'nexus_build_plans','status',{id:multi}))[0]?.status,{timeout:90000}).toBe('paid');
  roadmap=await rpc(client,'relystra_roadmap',{p_company_id:company});expect(roadmap.included).toHaveLength(4);const plans=await rows(page,'nexus_build_plans','id,items,status,deposit_cents,total_cents',{company_id:company});expect(plans.find(p=>p.id===one).items).toHaveLength(1);expect(plans.find(p=>p.id===multi).items).toHaveLength(2);expect(plans.filter(p=>[one,multi].includes(p.id)).flatMap(p=>p.items).every(i=>i.template_code!=='build_bid_intake')).toBe(true);
  // Prove the original scope can reach delivery while the optional packages remain queued.
  const card=(await rows(page,'nexus_system_cards','id',{project_id:original.id,company_id:company}))[0];
  const inputRequest=await rpc(page,'relystra_request_build_input',{p_build_id:card.id,p_title:'Two authorized sample bid records',p_purpose:'Populate and validate the accepted bid intake scope using only synthetic records.',p_examples:'CSV with request ID, site, owner and status',p_required:true});
  await expect(rpc(client,'relystra_review_build_input',{p_request_id:inputRequest,p_accept:true,p_note:'A client cannot accept their own input.'})).rejects.toThrow(/Administrator/);
  const uploaded=await client.evaluate(async({company,project,requestId})=>{const {persistEvidence}=await import('/portal-evidence-upload.js');return persistEvidence(window.NexusPortal.sb,{file:new File(['id,site,owner,status\nQA-001,Sample North Site,QA Coordinator,received\nQA-002,Sample South Site,QA Reviewer,needs clarification\n'],'synthetic-bid-inputs.csv',{type:'text/csv'}),companyId:company,userId:window.NexusPortal.state.user.id,projectId:project,requestId});},{company,project:original.id,requestId:inputRequest});
  expect(uploaded.id).toBeTruthy();
  await rpc(page,'relystra_review_build_input',{p_request_id:inputRequest,p_accept:true,p_note:'Reviewed the two labeled synthetic rows against the agreed bid intake fields; approved for this Build only.'});
  await rpc(page,'relystra_save_brief',{p_build_id:card.id,p_patch:{tools_platforms:['Published synthetic estimate register'],users_roles:['Synthetic QA Owner'],automation_requirements:['None'],integrations:['None'],assumptions:['Two authorized synthetic records'],risks:['Browser-local storage requires a backup'],test_inputs:['QA-001 and QA-002']},p_approve:true});
  const artifact=await clientContext.newPage();await artifact.goto('/delivery/qa-estimate-intake-register/');
  const records=[{id:'QA-001',site:'Sample North Site',contact:'qa-contact@example.invalid',scope:'lobby floor estimate',urgency:'normal',owner:'QA Coordinator',status:'received',due:'2026-10-10',source:'Synthetic Discovery'},{id:'QA-002',site:'Sample South Site',contact:'qa-backup@example.invalid',scope:'window estimate',urgency:'urgent',owner:'QA Reviewer',status:'needs clarification',due:'2026-10-11',source:'Synthetic Discovery'}];
  await artifact.locator('#importFile').setInputFiles({name:'synthetic-intake.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'relystra-qa-intake',version:1,records}))});await artifact.getByRole('button',{name:'Replace with validated backup',exact:true}).click();await artifact.reload();await expect(artifact.locator('#count')).toHaveText('2 saved');await artifact.screenshot({path:info.outputPath('populated-deliverable.png'),fullPage:true});
  const tasks=await rows(page,'nexus_tasks','id,sort_order',{build_id:card.id,work_kind:'build_task'});for(const task of tasks.sort((a,b)=>a.sort_order-b.sort_order))await rpc(page,'relystra_set_build_task',{p_task_id:task.id,p_complete:true,p_note:'Synthetic acceptance verified populated register, persistence, documented usage and backup.'});
  const content={description:'Synthetic QA bid intake register populated with the two authorized example requests.',preview_url:new URL('/delivery/qa-estimate-intake-register/',info.project.use.baseURL).href,what_to_test:['Confirm QA-001 and QA-002 are present; export and restore a validated backup'],tutorial:{what:'Track bid request ownership and status',steps:['Open the supplied register and restore the supplied backup','Review owner, status and next date for each request','Export a new backup after changes'],when:'Review incoming requests each working day and retain a backup after updates',troubleshooting:'Restore the last validated backup; ask Relystra about errors. No automatic outreach or bid submission.'},faq:[{question:'Does this send bids or messages?',answer:'No. This agreed register keeps the workflow manual.'}],known_limitations:['Synthetic acceptance artifact; browser-local storage. Export a backup after changes.']};
  await rpc(page,'relystra_save_delivery',{p_build_id:card.id,p_content:content});const checks=Object.fromEntries(['functionality','outputs','permissions','integrations','links','error_states','input_validation','data_behavior','mobile_usability','client_usability','documentation','faq','support_grounding'].map(k=>[k,{status:['integrations'].includes(k)?'not_applicable':'pass',evidence:'Synthetic acceptance: populated browser register, retained records, reviewed usage guide; related automated register and tenant tests pass. '+info.title}]));
  await rpc(page,'relystra_record_qa',{p_build_id:card.id,p_kind:'internal',p_checks:checks});const draft=await rpc(page,'relystra_publish_draft',{p_project_id:original.id});await rpc(client,'relystra_review_build',{p_build_id:card.id,p_draft_id:draft,p_decision:'approve',p_note:'Synthetic client verified the supplied example register and usage instructions.'});await rpc(page,'relystra_record_qa',{p_build_id:card.id,p_kind:'final',p_checks:checks});await expect(rpc(page,'relystra_publish_final',{p_project_id:original.id})).rejects.toThrow(/balance/);
  const balance=await rpc(client,'relystra_create_balance_plan',{p_plan_id:accepted.plan_id});const balancePay=await checkout(client,balance);expect(balancePay.livemode).toBe(false);await payTest(paymentPage,balancePay.url);await expect.poll(async()=>(await rows(page,'nexus_build_plans','status',{id:balance}))[0]?.status,{timeout:90000}).toBe('paid');
  const final=await rpc(page,'relystra_publish_final',{p_project_id:original.id});expect(await rpc(page,'relystra_publish_final',{p_project_id:original.id})).toBe(final);
  await client.goto(`/portal?company=${company}&project=${original.id}&section=final-package`);await expect(client.getByRole('heading',{name:'Final Package',exact:true})).toBeVisible({timeout:45000});await client.locator('#nexus-client-final-package').getByText('FAQs and limitations',{exact:true}).click();await expect(client.locator('#nexus-client-final-package').getByText('Known limitations',{exact:true})).toBeVisible();await client.screenshot({path:info.outputPath('final-handoff.png'),fullPage:true});
  const summary=await rpc(client,'relystra_payment_summary',{p_company_id:company});expect(summary.find(p=>p.plan_id===accepted.plan_id).balance_cents).toBe(0);expect((await rows(page,'nexus_projects','id',{company_id:company}))).toHaveLength(3);
  console.log('COMMERCIAL_PRODUCTION_ACCEPTANCE',JSON.stringify({company,reportId,diagnosis:run.id,initialPlan:accepted.plan_id,onePlan:one,multiplePlan:multi,balancePlan:balance,initialProject:original.id,finalPackage:final,qualified:proposed.length,builds:4,mode:'Stripe test; no funds moved'}));
 }finally{await prospectContext.close();await clientContext.close();await payments.close()}
});
