import {test,expect} from '@playwright/test';
const adminEmail=process.env.NEXUS_QA_ADMIN_EMAIL,adminPassword=process.env.NEXUS_QA_ADMIN_PASSWORD,clientEmail=process.env.NEXUS_QA_CLIENT_EMAIL,clientPassword=process.env.NEXUS_QA_CLIENT_PASSWORD,qaCompany=process.env.NEXUS_QA_COMPANY_NAME;
const clientTabs=[['overview','Today'],['intake','Intake'],['data-room','Data Room'],['action-queue','Actions'],['roadmap','Roadmap'],['ledger','Value'],['inbox','Inbox']];
function meaningful(messages){return messages.filter(text=>!/favicon|cloudflareinsights|analytics|ResizeObserver loop|Error performing TLS handshake: An unexpected TLS packet was received\./i.test(text))}
async function signIn(page,email,password){await page.goto('/portal.html',{waitUntil:'domcontentloaded'});await page.locator('#signInEmail').fill(email);await page.locator('#signInPassword').fill(password);await page.locator('#signInBtn').click();await expect(page.locator('#portalApp')).toBeVisible({timeout:25_000})}
async function noOverflow(page){const dims=await page.evaluate(()=>({s:document.documentElement.scrollWidth,c:document.documentElement.clientWidth}));expect(dims.s).toBeLessThanOrEqual(dims.c+1)}

test('public auth surface remains stable and touch safe',async({page})=>{const errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.goto('/portal.html',{waitUntil:'domcontentloaded'});await expect(page.locator('#signInForm')).toBeVisible();await page.locator('#tabCreate').click();await expect(page.locator('#createForm')).toBeVisible();await page.locator('#tabSignIn').click();for(const selector of ['#tabSignIn','#tabCreate','#signInBtn']){const box=await page.locator(selector).boundingBox();expect(box?.height||0).toBeGreaterThanOrEqual(40)}await noOverflow(page);expect(meaningful(errors)).toEqual([])});

test.describe('authenticated client control room',()=>{test.skip(!clientEmail||!clientPassword,'Dedicated Nexus QA client credentials are required.');test('seven tabs, intake, Data Room and health matrix pass',async({page})=>{const errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await signIn(page,clientEmail,clientPassword);const nav=page.locator('#nccPrimaryNav [data-client-view]');await expect(nav).toHaveCount(7);expect(await nav.allTextContents()).toEqual(clientTabs.map(([,label])=>label));for(const [index,[key]] of clientTabs.entries()){await nav.nth(index).click();await expect(page.locator(`#ncc-${key}`)).toBeVisible();await expect(nav.nth(index)).toHaveAttribute('aria-selected','true')}await page.locator('[data-client-view="intake"]').click();await expect(page.locator('.ncc-wizard-steps')).toBeVisible();await page.locator('[data-client-view="data-room"]').click();await expect(page.locator('[data-room-dropzone]')).toBeVisible();await expect(page.locator('#uploadForm')).toBeVisible();await expect.poll(async()=>page.evaluate(()=>typeof window.__NEXUS_HEALTH_CHECK)).toBe('function');const report=await page.evaluate(()=>window.__NEXUS_HEALTH_CHECK());expect(report.status,JSON.stringify(report.matrix.filter(row=>row.result==='FAILED'))).toBe('PASSED');expect(report.failed).toBe(0);await noOverflow(page);expect(meaningful(errors)).toEqual([])});test('company selector updates without reload',async({page})=>{await signIn(page,clientEmail,clientPassword);const select=page.locator('#companySelect'),values=await select.locator('option').evaluateAll(options=>options.map(o=>o.value).filter(Boolean));if(qaCompany)expect(await select.locator('option').allTextContents()).toContain(qaCompany);if(values.length>1){const first=await select.inputValue(),second=values.find(value=>value!==first);await select.selectOption(second);await expect.poll(async()=>page.evaluate(()=>window.NexusPortal?.state?.companyId)).toBe(second);await expect(page.locator('#nccWorkspaceContext b')).not.toHaveText('')}})});

test.describe('administrator command center',()=>{test.skip(!adminEmail||!adminPassword,'Dedicated Nexus QA administrator credentials are required.');test('Master View and health matrix pass',async({page})=>{const errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await signIn(page,adminEmail,adminPassword);if(qaCompany){const select=page.locator('#companySelect');if((await select.locator('option').allTextContents()).includes(qaCompany))await select.selectOption({label:qaCompany})}await expect(page.locator('#nexusAdminMasterButton')).toBeVisible();await page.locator('#nexusAdminMasterButton').click();await expect(page.locator('#nexusAdminMaster')).toHaveClass(/show/);await page.locator('[data-admin-tab="builder"]').click();await expect(page.locator('#nacBuilder')).toHaveClass(/active/);await page.locator('#nacClose').click();await expect(page.locator('#nexusAdminMaster')).not.toHaveClass(/show/);const report=await page.evaluate(()=>window.__NEXUS_HEALTH_CHECK());expect(report.status,JSON.stringify(report.matrix.filter(row=>row.result==='FAILED'))).toBe('PASSED');expect(meaningful(errors)).toEqual([])})});
